//go:build (!linux && !windows) || !cgo

package player

import (
	"fmt"

	"moonbasic/runtime"
	"moonbasic/vm/value"
)

func registerPlayerCharGetAPI(m *Module, reg runtime.Registrar) {
	stubGet := func(rt *runtime.Runtime, args ...value.Value) (value.Value, error) {
		_ = rt
		_ = args
		return value.Nil, fmt.Errorf("%s", errPlayerRequiresCGOJolt)
	}
	reg.Register("PLAYER.GETPOSITIONX", "player", stubGet)
	reg.Register("PLAYER.GETPOSITIONY", "player", stubGet)
	reg.Register("PLAYER.GETPOSITIONZ", "player", stubGet)
	reg.Register("PLAYER.GETROTATIONPITCH", "player", stubGet)
	reg.Register("PLAYER.GETROTATIONYAW", "player", stubGet)
	reg.Register("PLAYER.GETROTATIONROLL", "player", stubGet)
	reg.Register("PLAYER.GETVELOCITYX", "player", stubGet)
	reg.Register("PLAYER.GETVELOCITYY", "player", stubGet)
	reg.Register("PLAYER.GETVELOCITYZ", "player", stubGet)
	reg.Register("PLAYER.GETSPEED", "player", stubGet)
	reg.Register("PLAYER.GETONSLOPE", "player", stubGet)
	reg.Register("PLAYER.GETONWALL", "player", stubGet)
	reg.Register("PLAYER.GETSLOPEANGLE", "player", stubGet)
	reg.Register("PLAYER.GETISJUMPING", "player", stubGet)
	reg.Register("PLAYER.GETISFALLING", "player", stubGet)
	reg.Register("PLAYER.GETMAXSLOPE", "player", stubGet)
	reg.Register("PLAYER.GETSTEPHEIGHT", "player", stubGet)
	reg.Register("PLAYER.GETGRAVITYSCALE", "player", stubGet)
	reg.Register("PLAYER.GETFRICTION", "player", stubGet)
	reg.Register("PLAYER.GETSNAPDISTANCE", "player", stubGet)
	reg.Register("PLAYER.GETISSLIDING", "player", stubGet)
	reg.Register("PLAYER.GETCEILING", "player", stubGet)
	reg.Register("PLAYER.GETGROUNDVELOCITYX", "player", stubGet)
	reg.Register("PLAYER.GETGROUNDVELOCITYY", "player", stubGet)
	reg.Register("PLAYER.GETGROUNDVELOCITYZ", "player", stubGet)
	reg.Register("PLAYER.GETHEIGHT", "player", stubGet)
	reg.Register("PLAYER.GETRADIUS", "player", stubGet)
	reg.Register("PLAYER.GETLAYER", "player", stubGet)
	reg.Register("PLAYER.GETMASK", "player", stubGet)
	reg.Register("PLAYER.GETCOLLISIONENABLED", "player", stubGet)

	reg.Register("CHAR.GETPOSITIONX", "player", stubGet)
	reg.Register("CHAR.GETPOSITIONY", "player", stubGet)
	reg.Register("CHAR.GETPOSITIONZ", "player", stubGet)
	reg.Register("CHAR.GETROTATIONPITCH", "player", stubGet)
	reg.Register("CHAR.GETROTATIONYAW", "player", stubGet)
	reg.Register("CHAR.GETROTATIONROLL", "player", stubGet)
	reg.Register("CHAR.GETVELOCITYX", "player", stubGet)
	reg.Register("CHAR.GETVELOCITYY", "player", stubGet)
	reg.Register("CHAR.GETVELOCITYZ", "player", stubGet)
	reg.Register("CHAR.GETSPEED", "player", stubGet)
	reg.Register("CHAR.GETONSLOPE", "player", stubGet)
	reg.Register("CHAR.GETONWALL", "player", stubGet)
	reg.Register("CHAR.GETSLOPEANGLE", "player", stubGet)
	reg.Register("CHAR.GETISJUMPING", "player", stubGet)
	reg.Register("CHAR.GETISFALLING", "player", stubGet)
	reg.Register("CHAR.GETMAXSLOPE", "player", stubGet)
	reg.Register("CHAR.GETSTEPHEIGHT", "player", stubGet)
	reg.Register("CHAR.GETGRAVITYSCALE", "player", stubGet)
	reg.Register("CHAR.GETFRICTION", "player", stubGet)
	reg.Register("CHAR.GETSNAPDISTANCE", "player", stubGet)
	reg.Register("CHAR.GETISSLIDING", "player", stubGet)
	reg.Register("CHAR.GETCEILING", "player", stubGet)
	reg.Register("CHAR.GETGROUNDVELOCITYX", "player", stubGet)
	reg.Register("CHAR.GETGROUNDVELOCITYY", "player", stubGet)
	reg.Register("CHAR.GETGROUNDVELOCITYZ", "player", stubGet)
	reg.Register("CHAR.GETHEIGHT", "player", stubGet)
	reg.Register("CHAR.GETRADIUS", "player", stubGet)
	reg.Register("CHAR.GETLAYER", "player", stubGet)
	reg.Register("CHAR.GETMASK", "player", stubGet)
	reg.Register("CHAR.GETCOLLISIONENABLED", "player", stubGet)

	reg.Register("PLAYER.GETX", "player", stubGet)
	reg.Register("PLAYER.GETY", "player", stubGet)
	reg.Register("PLAYER.GETZ", "player", stubGet)
	reg.Register("PLAYER.GETPITCH", "player", stubGet)
	reg.Register("PLAYER.GETYAW", "player", stubGet)
	reg.Register("PLAYER.GETROLL", "player", stubGet)
	reg.Register("PLAYER.GETGROUNDED", "player", stubGet)
	reg.Register("PLAYER.GETGRAVITY", "player", stubGet)
	reg.Register("PLAYER.GETCAPSULERADIUS", "player", stubGet)
	reg.Register("PLAYER.GETCAPSULEHEIGHT", "player", stubGet)
	reg.Register("PLAYER.GETSHAPETYPE", "player", stubGet)

	reg.Register("CHAR.GETX", "player", stubGet)
	reg.Register("CHAR.GETY", "player", stubGet)
	reg.Register("CHAR.GETZ", "player", stubGet)
	reg.Register("CHAR.GETPITCH", "player", stubGet)
	reg.Register("CHAR.GETYAW", "player", stubGet)
	reg.Register("CHAR.GETROLL", "player", stubGet)
	reg.Register("CHAR.GETGROUNDED", "player", stubGet)
	reg.Register("CHAR.GETGRAVITY", "player", stubGet)
	reg.Register("CHAR.GETCAPSULERADIUS", "player", stubGet)
	reg.Register("CHAR.GETCAPSULEHEIGHT", "player", stubGet)
	reg.Register("CHAR.GETSHAPETYPE", "player", stubGet)
}