package player

import (
	"moonbasic/runtime"
)

func registerPlayerCommands(m *Module, reg runtime.Registrar) {
	// Standard CHARACTER.* and CHARACTERREF.* (Core)
	reg.Register("CHARACTER.CREATE", "player", runtime.AdaptLegacy(m.playerCharacterCreate))
	reg.Register("CHARACTERREF.ADDVELOCITY", "player", runtime.AdaptLegacy(m.charRefAddVel))
	reg.Register("CHARACTERREF.SETLINEARVELOCITY", "player", runtime.AdaptLegacy(m.charRefSetVel))
	reg.Register("CHARACTERREF.SETVELOCITY", "player", runtime.AdaptLegacy(m.charRefSetVel))
	reg.Register("CHARACTERREF.SETSNAPDISTANCE", "player", runtime.AdaptLegacy(m.charRefSetSnapDist))
	reg.Register("CHARACTERREF.SETSTICKDOWN", "player", runtime.AdaptLegacy(m.charRefSetSnapDist)) // Alias
	reg.Register("CHARACTERREF.UPDATE", "player", runtime.AdaptLegacy(m.charRefUpdate))
	reg.Register("CHARACTERREF.UPDATEMOVE", "player", runtime.AdaptLegacy(m.charRefUpdate))
	reg.Register("CHARACTERREF.JUMP", "player", runtime.AdaptLegacy(m.charRefJump))
	reg.Register("CHARACTERREF.MOVEWITHCAMERA", "player", runtime.AdaptLegacy(m.charRefMoveWithCam))
	reg.Register("CHARACTERREF.SETMAXSLOPE", "player", runtime.AdaptLegacy(m.charRefSetMaxSlope))
	reg.Register("CHARACTERREF.SETSTEPHEIGHT", "player", runtime.AdaptLegacy(m.charRefSetStepHeight))
	reg.Register("CHARACTERREF.ISGROUNDED", "player", runtime.AdaptLegacy(m.charRefIsGrounded))
	reg.Register("CHARACTERREF.SETPOSITION", "player", runtime.AdaptLegacy(m.charRefSetPos))
	reg.Register("CHARACTERREF.GETPOSITION", "player", runtime.AdaptLegacy(m.charRefGetPos))
	reg.Register("CHARACTERREF.FREE", "player", runtime.AdaptLegacy(m.charRefFree))
	reg.Register("CHARACTERREF.GETGROUNDSTATE", "player", runtime.AdaptLegacy(m.charRefGetGroundState))
	reg.Register("CHARACTERREF.SETGRAVITY", "player", runtime.AdaptLegacy(m.charRefSetGravityScale))
	reg.Register("CHARACTERREF.SETGRAVITYSCALE", "player", runtime.AdaptLegacy(m.charRefSetGravityScale))
	reg.Register("CHARACTERREF.SETFRICTION", "player", runtime.AdaptLegacy(m.charRefSetFriction))
	reg.Register("CHARACTERREF.SETPADDING", "player", runtime.AdaptLegacy(m.charRefSetPadding))
	reg.Register("CHARACTERREF.SETBOUNCE", "player", runtime.AdaptLegacy(m.charRefSetBounce))
	reg.Register("CHARACTERREF.GETSPEED", "player", runtime.AdaptLegacy(m.charRefGetSpeed))
	reg.Register("CHARACTERREF.ISMOVING", "player", runtime.AdaptLegacy(m.charRefIsMoving))

	// PLAYER.* Aliases (Easy Mode)
	reg.Register("PLAYER.CREATE", "player", runtime.AdaptLegacy(m.playerCharacterCreate))
	reg.Register("PLAYER.MOVE", "player", runtime.AdaptLegacy(m.playerMove))
	reg.Register("PLAYER.JUMP", "player", runtime.AdaptLegacy(m.playerJump))
	reg.Register("PLAYER.ISGROUNDED", "player", runtime.AdaptLegacy(m.playerIsGrounded))
	reg.Register("PLAYER.GETGROUNDSTATE", "player", runtime.AdaptLegacy(m.playerGetGroundState))
	reg.Register("PLAYER.ISONSTEEPSLOPE", "player", runtime.AdaptLegacy(m.playerIsOnSteepSlope))
	reg.Register("PLAYER.SETSTEPHEIGHT", "player", runtime.AdaptLegacy(m.playerSetStepOffset))
	reg.Register("PLAYER.SETSLOPELIMIT", "player", runtime.AdaptLegacy(m.playerSetSlopeLimit))
	reg.Register("PLAYER.SETSTEPOFFSET", "player", runtime.AdaptLegacy(m.playerSetStepOffset))
	reg.Register("PLAYER.SETSTICKFLOOR", "player", runtime.AdaptLegacy(m.playerSetStickFloor))
	reg.Register("PLAYER.NAVTO", "player", runtime.AdaptLegacy(m.playerNavTo))
	reg.Register("PLAYER.NAVUPDATE", "player", runtime.AdaptLegacy(m.playerNavUpdate))
	reg.Register("PLAYER.TELEPORT", "player", runtime.AdaptLegacy(m.playerTeleport))
	reg.Register("PLAYER.SETGRAVITYSCALE", "player", runtime.AdaptLegacy(m.playerSetGravityScale))
	reg.Register("PLAYER.SETPADDING", "player", runtime.AdaptLegacy(m.charRefSetPadding))
	reg.Register("PLAYER.MOVEWITHCAMERA", "player", runtime.AdaptLegacy(m.charRefMoveWithCam))

    // Extras / High-level
	reg.Register("PLAYER.GETLOOKTARGET", "player", runtime.AdaptLegacy(m.playerGetLookTarget))
	reg.Register("PLAYER.GETNEARBY", "player", runtime.AdaptLegacy(m.playerGetNearby))
	reg.Register("PLAYER.ONTRIGGER", "player", runtime.AdaptLegacy(m.playerOnTrigger))
	reg.Register("PLAYER.SETSTATE", "player", runtime.AdaptLegacy(m.playerSetState))
	reg.Register("PLAYER.SYNCANIM", "player", runtime.AdaptLegacy(m.playerSyncAnim))
	reg.Register("PLAYER.GETVELOCITY", "player", runtime.AdaptLegacy(m.playerGetVelocity))
	reg.Register("CHARACTERREF.GETVELOCITY", "player", runtime.AdaptLegacy(m.playerGetVelocity))
	reg.Register("PLAYER.GETCROUCH", "player", runtime.AdaptLegacy(m.playerGetCrouch))
	reg.Register("PLAYER.SETCROUCH", "player", runtime.AdaptLegacy(m.playerSetCrouch))
	reg.Register("PLAYER.SWIM", "player", runtime.AdaptLegacy(m.playerSwim))
	reg.Register("PLAYER.GETSTANDNORMAL", "player", runtime.AdaptLegacy(m.playerGetStandNormal))
	reg.Register("PLAYER.PUSH", "player", runtime.AdaptLegacy(m.playerPush))
	reg.Register("PLAYER.GRAB", "player", runtime.AdaptLegacy(m.playerGrab))
	reg.Register("PLAYER.SETMASS", "player", runtime.AdaptLegacy(m.playerSetMass))
	reg.Register("PLAYER.GETSURFACETYPE", "player", runtime.AdaptLegacy(m.playerGetSurfaceType))
	reg.Register("PLAYER.SETFOVKICK", "player", runtime.AdaptLegacy(m.playerSetFovKick))
	reg.Register("PLAYER.GETFOVKICK", "player", runtime.AdaptLegacy(m.playerGetFovKick))

	// CHAR.* Aliases (Easy Mode)
	reg.Register("CHAR.MAKE", "player", runtime.AdaptLegacy(m.playerCharacterCreate))
	reg.Register("CHAR.SETSTEP", "player", runtime.AdaptLegacy(m.playerSetStepOffset))
	reg.Register("CHAR.SETSLOPE", "player", runtime.AdaptLegacy(m.playerSetSlopeLimit))
	reg.Register("CHAR.SETPADDING", "player", runtime.AdaptLegacy(m.charRefSetPadding))
	reg.Register("CHAR.MOVE", "player", runtime.AdaptLegacy(m.playerCharMoveDir))
	reg.Register("CHAR.MOVEWITHCAMERA", "player", runtime.AdaptLegacy(m.charRefMoveWithCam))
	reg.Register("CHAR.MOVEWITHCAM", "player", runtime.AdaptLegacy(m.charRefMoveWithCam))
	reg.Register("CHAR.NAVTO", "player", runtime.AdaptLegacy(m.playerNavTo))
	reg.Register("CHAR.NAVUPDATE", "player", runtime.AdaptLegacy(m.playerNavUpdate))
	reg.Register("CHAR.STICK", "player", runtime.AdaptLegacy(m.playerSetStickFloor))
	reg.Register("CHAR.ISGROUNDED", "player", runtime.AdaptLegacy(m.playerIsGrounded))
	reg.Register("CHAR.JUMP", "player", runtime.AdaptLegacy(m.playerJump))
	reg.Register("CHAR.GETGROUNDSTATE", "player", runtime.AdaptLegacy(m.playerGetGroundState))
	reg.Register("CHAR.ISONSTEEPSLOPE", "player", runtime.AdaptLegacy(m.playerIsOnSteepSlope))

	// NAV.* intent layer
	reg.Register("NAV.GOTO", "player", runtime.AdaptLegacy(m.playerNavTo))
	reg.Register("NAV.UPDATE", "player", runtime.AdaptLegacy(m.playerNavUpdate))
	reg.Register("NAV.CHASE", "player", runtime.AdaptLegacy(m.playerNavChase))
	reg.Register("NAV.PATROL", "player", runtime.AdaptLegacy(m.playerNavPatrol))

	// ENTITYREF methods (for handle-bound calls)
	reg.Register("ENTITYREF.NAVUPDATE", "entity", runtime.AdaptLegacy(m.playerNavUpdate))
	reg.Register("ENTITYREF.ISGROUNDED", "entity", runtime.AdaptLegacy(m.playerIsGrounded))
	reg.Register("ENTITYREF.JUMP", "entity", runtime.AdaptLegacy(m.playerJump))

	registerPlayerCharGetAPI(m, reg)
	registerPlayerTerrainCommands(m, reg)
}
