"""Data, serialization, and file-IO manifest entries.

Covers: JSON.*, CONFIG.*, CSV.*, DB.*, ROWS.*, FILE.*, READLINE, WRITELINE,
        SEEKFILE, FILEPOS, FILESIZE, EOF, READBYTE, READSHORT, WRITEBYTE,
        WRITESHORT, WRITESTRING, UTIL.CREATEDIRECTORY, BANK/MEM commands.
Arities verified from runtime/data, runtime/config, runtime/fileio source.
"""

from .helpers import ntimes

ENTRIES = [
    # --- json extended ---
    ("JSON.APPEND", ["handle", "any"], None, "any"),
    ("JSON.CLEAR", ntimes("handle", 1), None, "any"),
    ("JSON.DELETE", ["handle", "string"], None, "any"),
    ("JSON.GETARRAY", ["handle", "string"], "handle", "any"),
    ("JSON.GETOBJECT", ["handle", "string"], "handle", "any"),
    ("JSON.HAS", ["handle", "string"], "bool", "any"),
    ("JSON.KEYS", ntimes("handle", 1), "handle", "any"),
    ("JSON.LEN", ntimes("handle", 1), "int", "any"),
    ("JSON.MAKEARRAY", [], "handle", "any"),
    ("JSON.MINIFY", ntimes("handle", 1), "string", "any"),
    ("JSON.PRETTY", ntimes("handle", 1), "string", "any"),
    ("JSON.QUERY", ["handle", "string"], "any", "any"),
    ("JSON.SETNULL", ["handle", "string"], None, "any"),
    ("JSON.TOCSV", ntimes("handle", 1), "string", "any"),
    ("JSON.TOFILE", ["handle", "string"], None, "any"),
    ("JSON.TOFILEPRETTY", ["handle", "string"], None, "any"),
    ("JSON.TYPE", ["handle", "string"], "string", "any"),
    # --- config ---
    ("CONFIG.LOAD", ntimes("string", 1), None, "any"),
    ("CONFIG.SAVE", ntimes("string", 1), None, "any"),
    ("CONFIG.GETINT", ntimes("string", 1), "int", "any"),
    ("CONFIG.GETFLOAT", ntimes("string", 1), "float", "any"),
    ("CONFIG.GETSTRING", ntimes("string", 1), "string", "any"),
    ("CONFIG.GETBOOL", ntimes("string", 1), "bool", "any"),
    ("CONFIG.SETINT", ["string", "int"], None, "any"),
    ("CONFIG.SETFLOAT", ["string", "float"], None, "any"),
    ("CONFIG.SETSTRING", ntimes("string", 2), None, "any"),
    ("CONFIG.SETBOOL", ["string", "bool"], None, "any"),
    ("CONFIG.HAS", ntimes("string", 1), "bool", "any"),
    ("CONFIG.DELETE", ntimes("string", 1), None, "any"),
    # --- csv ---
    ("CSV.LOAD", ntimes("string", 1), "handle", "any"),
    ("CSV.FROMSTRING", ntimes("string", 1), "handle", "any"),
    ("CSV.SAVE", ["handle", "string"], None, "any"),
    ("CSV.FREE", ntimes("handle", 1), None, "any"),
    ("CSV.ROWCOUNT", ntimes("handle", 1), "int", "any"),
    ("CSV.COLCOUNT", ntimes("handle", 1), "int", "any"),
    ("CSV.GET", ["handle", "int", "int"], "string", "any"),
    ("CSV.SET", ["handle", "int", "int", "string"], None, "any"),
    ("CSV.TOSTRING", ntimes("handle", 1), "string", "any"),
    ("CSV.TOJSON", ntimes("handle", 1), "handle", "any"),
    # --- db (sqlite) ---
    ("DB.OPEN", ntimes("string", 1), "handle", "any"),
    ("DB.CLOSE", ntimes("handle", 1), None, "any"),
    ("DB.EXEC", ["handle", "string"], None, "any"),
    ("DB.QUERY", ["handle", "string"], "handle", "any"),
    ("DB.QUERYJSON", ["handle", "string"], "handle", "any"),
    ("DB.PREPARE", ["handle", "string"], "handle", "any"),
    ("DB.STMTEXEC", ["handle", "any"], None, "any"),
    ("DB.STMTCLOSE", ntimes("handle", 1), None, "any"),
    ("DB.LASTINSERTID", ntimes("handle", 1), "int", "any"),
    ("DB.CHANGES", ntimes("handle", 1), "int", "any"),
    ("DB.ISOPEN", ntimes("handle", 1), "bool", "any"),
    ("DB.BEGIN", ntimes("handle", 1), None, "any"),
    ("DB.COMMIT", ntimes("handle", 1), None, "any"),
    ("DB.ROLLBACK", ntimes("handle", 1), None, "any"),
    ("ROWS.NEXT", ntimes("handle", 1), "bool", "any"),
    ("ROWS.GETINT", ["handle", "int"], "int", "any"),
    ("ROWS.GETFLOAT", ["handle", "int"], "float", "any"),
    ("ROWS.GETSTRING", ["handle", "int"], "string", "any"),
    ("ROWS.CLOSE", ntimes("handle", 1), None, "any"),
    # --- file extended ---
    ("FILE.CLOSE", ntimes("handle", 1), None, "any"),
    ("FILE.EOF", ntimes("handle", 1), "bool", "any"),
    ("FILE.READLINE", ntimes("handle", 1), "string", "any"),
    ("FILE.SEEK", ["handle", "int"], None, "any"),
    ("FILE.SIZE", ntimes("handle", 1), "int", "any"),
    ("FILE.TELL", ntimes("handle", 1), "int", "any"),
    ("FILE.WRITE", ["handle", "string"], None, "any"),
    ("FILE.WRITELN", ["handle", "string"], None, "any"),
    ("READLINE", ntimes("handle", 1), "string", "any"),
    ("WRITELINE", ["handle", "string"], None, "any"),
    ("SEEKFILE", ["handle", "int"], None, "any"),
    ("FILEPOS", ntimes("handle", 1), "int", "any"),
    ("FILESIZE", ntimes("handle", 1), "int", "any"),
    ("EOF", ntimes("handle", 1), "bool", "any"),
    ("READBYTE", ntimes("handle", 1), "int", "any"),
    ("READSHORT", ntimes("handle", 1), "int", "any"),
    ("WRITEBYTE", ["handle", "int"], None, "any"),
    ("WRITESHORT", ["handle", "int"], None, "any"),
    ("WRITESTRING", ["handle", "string"], None, "any"),
    ("UTIL.CREATEDIRECTORY", ntimes("string", 1), None, "any"),
    # --- bank (memory) ---
    ("CREATEBANK", ntimes("int", 1), "handle", "any"),
    ("FREEBANK", ntimes("handle", 1), None, "any"),
    ("RESIZEBANK", ["handle", "int"], None, "any"),
    ("BANKSIZE", ntimes("handle", 1), "int", "any"),
    ("COPYBANK", ["handle", "handle", "int", "int", "int"], None, "any"),
    ("READBANK", ["handle", "handle", "int", "int"], None, "any"),
    ("WRITEBANK", ["handle", "handle", "int", "int"], None, "any"),
    ("POKEBYTE", ["handle", "int", "int"], None, "any"),
    ("POKESHORT", ["handle", "int", "int"], None, "any"),
    ("POKEINT", ["handle", "int", "int"], None, "any"),
    ("POKEFLOAT", ["handle", "int", "float"], None, "any"),
    ("PEEKBYTE", ["handle", "int"], "int", "any"),
    ("PEEKSHORT", ["handle", "int"], "int", "any"),
    ("PEEKINT", ["handle", "int"], "int", "any"),
    ("PEEKFLOAT", ["handle", "int"], "float", "any"),
    ("MEM.RESIZE", ["handle", "int"], None, "any"),
    ("MEM.GETDOUBLE", ["handle", "int"], "float", "any"),
    ("MEM.SETDOUBLE", ["handle", "int", "float"], None, "any"),
]
