"""Persistent draw-object manifest entries.

Covers: DRAWPRIM2D.*, DRAWPRIM3D.*, DRAWTEXREC.*, DRAWTEXPRO.*,
        DRAWTEX2.*, TEXTDRAW.*, TEXTEXOBJ.*, and all factory calls
        (DRAWCIRCLE2, DRAWCUBE, TEXTOBJ, TEXTOBJEX, etc.).
Arities verified from runtime/draw (prim2d_wrapper_cgo.go,
prim3d_wrapper_cgo.go, texture_adv_wrappers_cgo.go,
obj_text_texture_cgo.go).
"""

from .helpers import ntimes

ENTRIES = [
    # --- drawprim2d wrapper object commands ---
    ("DRAWPRIM2D.POS", ["handle", "float", "float"], None, "rendering"),
    ("DRAWPRIM2D.SIZE", ["handle", "float"], None, "rendering"),        # overload: 2 or 3 args
    ("DRAWPRIM2D.SIZE", ["handle", "float", "float"], None, "rendering"),
    ("DRAWPRIM2D.COLOR", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("DRAWPRIM2D.COL", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("DRAWPRIM2D.OUTLINE", ["handle", "bool"], None, "rendering"),
    ("DRAWPRIM2D.P2", ["handle", "float", "float"], None, "rendering"),
    ("DRAWPRIM2D.P3", ["handle", "float", "float"], None, "rendering"),
    ("DRAWPRIM2D.RING", ["handle", "float", "float", "float", "float"], None, "rendering"),
    ("DRAWPRIM2D.SEGS", ["handle", "int"], None, "rendering"),
    ("DRAWPRIM2D.SIDES", ["handle", "int"], None, "rendering"),
    ("DRAWPRIM2D.ROT", ["handle", "float"], None, "rendering"),
    ("DRAWPRIM2D.THICK", ["handle", "float"], None, "rendering"),
    ("DRAWPRIM2D.DRAW", ntimes("handle", 1), None, "rendering"),
    ("DRAWPRIM2D.FREE", ntimes("handle", 1), None, "rendering"),
    # prim2d factory calls
    ("DRAWCIRCLE2", [], "handle", "rendering"),
    ("DRAWCIRCLE2W", [], "handle", "rendering"),
    ("DRAWELLIPSE2", [], "handle", "rendering"),
    ("DRAWELLIPSE2W", [], "handle", "rendering"),
    ("DRAWRECT2", [], "handle", "rendering"),
    ("DRAWRECT2W", [], "handle", "rendering"),
    ("DRAWLINE2", [], "handle", "rendering"),
    ("DRAWTRI2", [], "handle", "rendering"),
    ("DRAWTRI2W", [], "handle", "rendering"),
    ("DRAWRING2", [], "handle", "rendering"),
    ("DRAWRING2W", [], "handle", "rendering"),
    ("DRAWPOLY2", [], "handle", "rendering"),
    ("DRAWPOLY2W", [], "handle", "rendering"),
    # --- drawprim3d wrapper object commands ---
    ("DRAWPRIM3D.POS", ["handle", "float", "float", "float"], None, "rendering"),
    ("DRAWPRIM3D.SIZE", ["handle", "float"], None, "rendering"),
    ("DRAWPRIM3D.SIZE", ["handle", "float", "float", "float"], None, "rendering"),
    ("DRAWPRIM3D.COLOR", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("DRAWPRIM3D.COL", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("DRAWPRIM3D.WIRE", ["handle", "bool"], None, "rendering"),
    ("DRAWPRIM3D.RADIUS", ["handle", "float"], None, "rendering"),
    ("DRAWPRIM3D.ENDPOINT", ["handle", "float", "float", "float"], None, "rendering"),
    ("DRAWPRIM3D.CYL", ["handle", "float", "float", "float"], None, "rendering"),
    ("DRAWPRIM3D.BBOX", ["handle", "float", "float", "float", "float", "float", "float"], None, "rendering"),
    ("DRAWPRIM3D.SLICES", ["handle", "int"], None, "rendering"),
    ("DRAWPRIM3D.RINGS", ["handle", "int"], None, "rendering"),
    ("DRAWPRIM3D.GRID", ["handle", "int", "float"], None, "rendering"),
    ("DRAWPRIM3D.SETRAY", ["handle", "handle"], None, "rendering"),
    ("DRAWPRIM3D.SETTEXTURE", ["handle", "handle"], None, "rendering"),
    ("DRAWPRIM3D.SRCTEX", ["handle", "float", "float", "float", "float"], None, "rendering"),
    ("DRAWPRIM3D.DRAW", ntimes("handle", 1), None, "rendering"),
    ("DRAWPRIM3D.FREE", ntimes("handle", 1), None, "rendering"),
    # prim3d factory calls
    ("DRAWCUBE", [], "handle", "rendering"),
    ("DRAWCUBEWIRES", [], "handle", "rendering"),
    ("DRAWSPHERE", [], "handle", "rendering"),   # persistent obj, not immediate
    ("DRAWSPHEREW", [], "handle", "rendering"),
    ("DRAWCYLINDER", [], "handle", "rendering"),
    ("DRAWCYLINDERW", [], "handle", "rendering"),
    ("DRAWCAP", [], "handle", "rendering"),
    ("DRAWCAPW", [], "handle", "rendering"),
    ("DRAWPLANE", [], "handle", "rendering"),
    ("DRAWBBOX", [], "handle", "rendering"),
    ("DRAWRAY", [], "handle", "rendering"),
    ("DRAWLINE3D", [], "handle", "rendering"),
    ("DRAWPOINT3D", [], "handle", "rendering"),
    ("DRAWGRID3D", [], "handle", "rendering"),
    ("DRAWBILLBOARD", [], "handle", "rendering"),
    ("DRAWBILLBOARDREC", [], "handle", "rendering"),
    # --- text draw objects ---
    ("TEXTOBJ", ntimes("string", 1), "handle", "rendering"),
    ("TEXTDRAW.POS", ["handle", "int", "int"], None, "rendering"),
    ("TEXTDRAW.SIZE", ["handle", "int"], None, "rendering"),
    ("TEXTDRAW.COLOR", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("TEXTDRAW.COL", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("TEXTDRAW.SETTEXT", ["handle", "string"], None, "rendering"),
    ("TEXTDRAW.DRAW", ntimes("handle", 1), None, "rendering"),
    ("TEXTDRAW.FREE", ntimes("handle", 1), None, "rendering"),
    # text draw ex objects (font-based)
    ("TEXTOBJEX", ["handle", "string"], "handle", "rendering"),
    ("TEXTEXOBJ.POS", ["handle", "float", "float"], None, "rendering"),
    ("TEXTEXOBJ.SIZE", ["handle", "float"], None, "rendering"),
    ("TEXTEXOBJ.SPACING", ["handle", "float"], None, "rendering"),
    ("TEXTEXOBJ.COLOR", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("TEXTEXOBJ.SETTEXT", ["handle", "string"], None, "rendering"),
    ("TEXTEXOBJ.DRAW", ntimes("handle", 1), None, "rendering"),
    ("TEXTEXOBJ.FREE", ntimes("handle", 1), None, "rendering"),
    # --- texture draw 2 objects ---
    ("DRAWTEX2", ntimes("handle", 1), "handle", "rendering"),
    ("DRAWTEX2.POS", ["handle", "int", "int"], None, "rendering"),
    ("DRAWTEX2.COLOR", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("DRAWTEX2.COL", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("DRAWTEX2.SETTEXTURE", ["handle", "handle"], None, "rendering"),
    ("DRAWTEX2.DRAW", ntimes("handle", 1), None, "rendering"),
    ("DRAWTEX2.FREE", ntimes("handle", 1), None, "rendering"),
    # --- drawtexrec objects ---
    ("DRAWTEXREC", ntimes("handle", 1), "handle", "rendering"),
    ("DRAWTEXREC.SRC", ["handle", "float", "float", "float", "float"], None, "rendering"),
    ("DRAWTEXREC.POS", ["handle", "float", "float"], None, "rendering"),
    ("DRAWTEXREC.COLOR", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("DRAWTEXREC.COL", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("DRAWTEXREC.SETTEXTURE", ["handle", "handle"], None, "rendering"),
    ("DRAWTEXREC.DRAW", ntimes("handle", 1), None, "rendering"),
    ("DRAWTEXREC.FREE", ntimes("handle", 1), None, "rendering"),
    # --- drawtexpro objects ---
    ("DRAWTEXPRO", ntimes("handle", 1), "handle", "rendering"),
    ("DRAWTEXPRO.SRC", ["handle", "float", "float", "float", "float"], None, "rendering"),
    ("DRAWTEXPRO.DST", ["handle", "float", "float", "float", "float"], None, "rendering"),
    ("DRAWTEXPRO.ORIGIN", ["handle", "float", "float"], None, "rendering"),
    ("DRAWTEXPRO.ROT", ["handle", "float"], None, "rendering"),
    ("DRAWTEXPRO.COLOR", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("DRAWTEXPRO.COL", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("DRAWTEXPRO.SETTEXTURE", ["handle", "handle"], None, "rendering"),
    ("DRAWTEXPRO.DRAW", ntimes("handle", 1), None, "rendering"),
    ("DRAWTEXPRO.FREE", ntimes("handle", 1), None, "rendering"),
]
