"""Immediate-mode 2D/3D draw and text-helper manifest entries.

Covers: DRAW.*, DRAW3D.*, draw convenience (OVAL, DRAW.CENTERTEXT, …),
        GETTEXTCODEPOINTCOUNT, MEASURETEXT, MEASURETEXTEX.
Arities verified from runtime/draw source (shapes.go, lines.go, advanced.go,
text.go, shapes_sector_cgo.go, stub.go).
"""

from .helpers import ntimes

ENTRIES = [
    # --- draw 2d (pixel-ish coords: int; floats where runtime uses argFloat) ---
    ("DRAW.ARC", ntimes("float", 6) + ntimes("int", 4), None, "rendering"),
    (
        "DRAW.BILLBOARD",
        ["handle", "float", "float", "float", "float"] + ntimes("int", 4),
        None,
        "rendering",
    ),
    (
        "DRAW.BILLBOARDREC",
        ["handle", "float", "float", "float", "float", "float", "float", "float", "float"]
        + ntimes("int", 4),
        None,
        "rendering",
    ),
    ("DRAW.BOUNDINGBOX", ntimes("float", 6) + ntimes("int", 4), None, "rendering"),
    (
        "DRAW.CAPSULE",
        ntimes("float", 9) + ntimes("int", 2) + ntimes("int", 4),
        None,
        "rendering",
    ),
    (
        "DRAW.CAPSULEWIRES",
        ntimes("float", 9) + ntimes("int", 2) + ntimes("int", 4),
        None,
        "rendering",
    ),
    ("DRAW.CIRCLE", ntimes("int", 7), None, "rendering"),
    ("DRAW.CIRCLEGRADIENT", ntimes("int", 3) + ntimes("int", 8), None, "rendering"),
    ("DRAW.CIRCLELINES", ntimes("int", 7), None, "rendering"),
    ("DRAW.CIRCLESECTOR", ntimes("int", 6) + ntimes("int", 4), None, "rendering"),
    ("DRAW.CUBE", ntimes("float", 7) + ntimes("int", 4), None, "rendering"),
    ("DRAW.CUBEWIRES", ntimes("float", 7) + ntimes("int", 4), None, "rendering"),
    ("DRAW.CYLINDER", ntimes("float", 7) + ntimes("int", 4), None, "rendering"),
    ("DRAW.CYLINDERWIRES", ntimes("float", 7) + ntimes("int", 4), None, "rendering"),
    ("DRAW.DOT", ntimes("int", 2) + ntimes("float", 1) + ntimes("int", 4), None, "rendering"),
    ("DRAW.ELLIPSE", ntimes("int", 8), None, "rendering"),
    ("DRAW.ELLIPSELINES", ntimes("int", 8), None, "rendering"),
    ("DRAW.GETPIXELCOLOR", ntimes("int", 2), "handle", "rendering"),
    ("DRAW.GRID", ["int", "float"], None, "rendering"),
    ("DRAW.GRID2D", ntimes("int", 5), None, "rendering"),
    ("DRAW.LINE", ntimes("int", 8), None, "rendering"),
    ("DRAW.LINE3D", ntimes("float", 6) + ntimes("int", 4), None, "rendering"),
    ("DRAW.LINEBEZIER", ntimes("float", 5) + ntimes("int", 4), None, "rendering"),
    ("DRAW.LINEBEZIERCUBIC", ntimes("float", 9) + ntimes("int", 4), None, "rendering"),
    ("DRAW.LINEBEZIERQUAD", ntimes("float", 7) + ntimes("int", 4), None, "rendering"),
    ("DRAW.LINEEX", ntimes("float", 5) + ntimes("int", 4), None, "rendering"),
    ("DRAW.PIXEL", ntimes("int", 6), None, "rendering"),
    ("DRAW.PIXELV", ntimes("float", 2) + ntimes("int", 4), None, "rendering"),
    ("DRAW.PLANE", ntimes("float", 6) + ntimes("int", 4), None, "rendering"),
    ("DRAW.POINT3D", ntimes("float", 3) + ntimes("int", 4), None, "rendering"),
    ("DRAW.POLY", ntimes("int", 5) + ntimes("int", 4), None, "rendering"),
    ("DRAW.POLYLINES", ntimes("int", 5) + ntimes("float", 1) + ntimes("int", 4), None, "rendering"),
    ("DRAW.RAY", ["handle"] + ntimes("int", 4), None, "rendering"),
    ("DRAW.RECTGRAD", ntimes("int", 4) + ntimes("int", 16), None, "rendering"),
    ("DRAW.RECTGRADH", ntimes("int", 12), None, "rendering"),
    ("DRAW.RECTGRADV", ntimes("int", 12), None, "rendering"),
    ("DRAW.RECTLINES", ntimes("int", 5) + ntimes("float", 1) + ntimes("int", 4), None, "rendering"),
    ("DRAW.RECTPRO", ntimes("int", 4) + ntimes("float", 3) + ntimes("int", 4), None, "rendering"),
    ("DRAW.RING", ntimes("int", 7) + ntimes("float", 2) + ntimes("int", 4), None, "rendering"),
    ("DRAW.RINGLINES", ntimes("int", 7) + ntimes("float", 2) + ntimes("int", 4), None, "rendering"),
    ("DRAW.SETPIXELCOLOR", ntimes("int", 6), None, "rendering"),
    ("DRAW.SPHERE", ntimes("float", 4) + ntimes("int", 4), None, "rendering"),
    ("DRAW.SPHEREWIRES", ntimes("float", 4) + ntimes("int", 2) + ntimes("int", 4), None, "rendering"),
    ("DRAW.SPLINEBASIS", ["handle", "float"] + ntimes("int", 4), None, "rendering"),
    ("DRAW.SPLINEBEZIERCUBIC", ["handle", "float"] + ntimes("int", 4), None, "rendering"),
    ("DRAW.SPLINEBEZIERQUAD", ["handle", "float"] + ntimes("int", 4), None, "rendering"),
    ("DRAW.SPLINECATMULLROM", ["handle", "float"] + ntimes("int", 4), None, "rendering"),
    ("DRAW.SPLINELINEAR", ["handle", "float"] + ntimes("int", 4), None, "rendering"),
    ("DRAW.TEXT", ["string"] + ntimes("int", 7), None, "rendering"),
    (
        "DRAW.TEXTEX",
        ["handle", "string", "float", "float", "float", "float"] + ntimes("int", 4),
        None,
        "rendering",
    ),
    (
        "DRAW.TEXTFONT",
        ["handle", "string", "float", "float", "float", "float"] + ntimes("int", 4),
        None,
        "rendering",
    ),
    (
        "DRAW.TEXTFONTWIDTH",
        ["handle", "string", "float", "float"],
        "float",
        "rendering",
    ),
    (
        "DRAW.TEXTPRO",
        ["handle", "string", "float", "float", "float", "float", "float", "float", "float"]
        + ntimes("int", 4),
        None,
        "rendering",
    ),
    (
        "DRAW.TEXTUREEX",
        ["handle", "float", "float", "float", "float"] + ntimes("int", 4),
        None,
        "rendering",
    ),
    ("DRAW.TEXTUREFLIPPED", ntimes("handle", 1), None, "rendering"),
    ("DRAW.TEXTUREFULL", ntimes("handle", 1), None, "rendering"),
    (
        "DRAW.TEXTUREPRO",
        ["handle", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"]
        + ntimes("int", 4),
        None,
        "rendering",
    ),
    (
        "DRAW.TEXTUREREC",
        ["handle", "float", "float", "float", "float", "float", "float"] + ntimes("int", 4),
        None,
        "rendering",
    ),
    (
        "DRAW.TEXTURETILED",
        ["handle"] + ntimes("float", 12) + ntimes("int", 4),
        None,
        "rendering",
    ),
    (
        "DRAW.TEXTUREV",
        ["handle", "float", "float"] + ntimes("int", 4),
        None,
        "rendering",
    ),
    ("DRAW.TEXTWIDTH", ["string", "int"], "int", "rendering"),
    ("DRAW.TRIANGLE", ntimes("int", 6) + ntimes("int", 4), None, "rendering"),
    ("DRAW.TRIANGLELINES", ntimes("int", 6) + ntimes("int", 4), None, "rendering"),
    # --- draw 3d ---
    ("DRAW3D.BBOX", ntimes("float", 6) + ntimes("int", 4), None, "rendering"),
    (
        "DRAW3D.BILLBOARD",
        ["handle", "float", "float", "float", "float"] + ntimes("int", 4),
        None,
        "rendering",
    ),
    (
        "DRAW3D.BILLBOARDREC",
        ["handle", "float", "float", "float", "float", "float", "float", "float", "float"]
        + ntimes("int", 4),
        None,
        "rendering",
    ),
    (
        "DRAW3D.CAPSULE",
        ntimes("float", 9) + ntimes("int", 2) + ntimes("int", 4),
        None,
        "rendering",
    ),
    (
        "DRAW3D.CAPSULEWIRES",
        ntimes("float", 9) + ntimes("int", 2) + ntimes("int", 4),
        None,
        "rendering",
    ),
    ("DRAW3D.CUBE", ntimes("float", 7) + ntimes("int", 4), None, "rendering"),
    ("DRAW3D.CUBEWIRES", ntimes("float", 7) + ntimes("int", 4), None, "rendering"),
    ("DRAW3D.CYLINDER", ntimes("float", 7) + ntimes("int", 4), None, "rendering"),
    ("DRAW3D.CYLINDERWIRES", ntimes("float", 7) + ntimes("int", 4), None, "rendering"),
    ("DRAW3D.GRID", ["int", "float"], None, "rendering"),
    ("DRAW3D.LINE", ntimes("float", 6) + ntimes("int", 4), None, "rendering"),
    ("DRAW3D.PLANE", ntimes("float", 6) + ntimes("int", 4), None, "rendering"),
    ("DRAW3D.POINT", ntimes("float", 3) + ntimes("int", 4), None, "rendering"),
    ("DRAW3D.RAY", ["handle"] + ntimes("int", 4), None, "rendering"),
    ("DRAW3D.SPHERE", ntimes("float", 4) + ntimes("int", 4), None, "rendering"),
    ("DRAW3D.SPHEREWIRES", ntimes("float", 4) + ntimes("int", 2) + ntimes("int", 4), None, "rendering"),
    # --- text helpers (also reachable as bare calls) ---
    ("GETTEXTCODEPOINTCOUNT", ntimes("string", 1), "int", "any"),
    ("MEASURETEXT", ["string", "int"], "int", "any"),
    ("MEASURETEXTEX", ["handle", "string", "float", "float"], "handle", "any"),
    # --- draw convenience (from stub.go + shapes + advanced + text) ---
    ("DRAW.CENTERTEXT", ["string"] + ntimes("int", 7), None, "rendering"),
    ("DRAW.RIGHTTEXT", ["string"] + ntimes("int", 7), None, "rendering"),
    ("DRAW.SHADOWTEXT", ["string"] + ntimes("int", 11), None, "rendering"),
    ("DRAW.OUTLINETEXT", ["string"] + ntimes("int", 11), None, "rendering"),
    ("DRAW.PROGRESSBAR", ntimes("int", 5) + ntimes("float", 1) + ntimes("int", 8), None, "rendering"),
    ("DRAW.HEALTHBAR", ntimes("int", 5) + ntimes("float", 1) + ntimes("int", 12), None, "rendering"),
    ("DRAW.CROSSHAIR", ntimes("int", 6), None, "rendering"),
    ("DRAW.RECTGRID", ntimes("int", 6), None, "rendering"),
    ("DRAW.OVAL", ntimes("int", 8), None, "rendering"),
    ("OVAL", ntimes("int", 8), None, "rendering"),
]
