"""Entity manifest entries.

Covers: ENTITY.*, ENTITYREF.*, ENT.*, Blitz entity-compat globals
        (EntityDistance, CreateMesh, CopyEntity, etc.), brush commands,
        terrain commands, picking, collision, sprite, and APPLYENTITY*.
Arities verified from runtime/mbentity source (entity_blitz_cgo.go,
entity_blitz_facade_cgo.go, brush_blitz_cgo.go).
"""

from .helpers import ntimes

ENTRIES = [
    # --- entity blitz compat ---
    ("ENTITYDISTANCE", ["handle", "handle"], "float", "any"),
    ("ENTITYINVIEW", ntimes("handle", 1), "bool", "any"),
    ("ENTITYFX", ["handle", "int"], None, "any"),
    ("ENTITYORDER", ["handle", "int"], None, "any"),
    ("ENTITYPARENT", ["handle", "handle"], None, "any"),
    ("ENTITYVISIBLE", ["handle", "bool"], None, "any"),
    ("ENTITYNAME", ntimes("handle", 1), "string", "any"),
    ("ENTITYBOX", ["handle", "float", "float", "float", "float", "float", "float"], None, "any"),
    ("ENTITYAUTOFADE", ["handle", "float", "float"], None, "any"),
    ("ENTITYSCALEX", ntimes("handle", 1), "float", "any"),
    ("ENTITYSCALEY", ntimes("handle", 1), "float", "any"),
    ("ENTITYSCALEZ", ntimes("handle", 1), "float", "any"),
    ("ENTITYPICK", ["handle", "float"], "handle", "any"),
    ("COPYENTITY", ntimes("handle", 1), "handle", "any"),
    ("NAMEENTITY", ["handle", "string"], None, "any"),
    ("FINDCHILD", ["handle", "string"], "handle", "any"),
    ("GETCHILD", ["handle", "int"], "handle", "any"),
    ("GETPARENT", ntimes("handle", 1), "handle", "any"),
    ("COUNTCHILDREN", ntimes("handle", 1), "int", "any"),
    ("ALIGNTOVECTOR", ["handle", "float", "float", "float", "int", "float"], None, "any"),
    ("CREATEMESH", [], "handle", "any"),
    ("CREATESPHERE", ["int"], "handle", "any"),
    ("CREATECYLINDER", ["int"], "handle", "any"),
    ("CREATECONE", ["int"], "handle", "any"),
    ("CREATEPLANE", [], "handle", "any"),
    ("CREATESPRITE", [], "handle", "any"),
    ("CREATESPRITE3D", [], "handle", "any"),
    ("CREATETERRAIN", ["int"], "handle", "any"),
    ("CREATETEXTURE", ["int", "int", "int"], "handle", "any"),
    ("CREATEMIRROR", [], "handle", "any"),
    ("CREATEWORLD", [], "handle", "any"),
    ("CLEARWORLD", [], None, "any"),
    ("ADDSURFACE", ["handle", "handle"], "handle", "any"),
    ("FITMESH", ["handle", "float", "float", "float", "float", "float", "float", "int"], None, "any"),
    ("FLIPMESH", ntimes("handle", 1), None, "any"),
    ("UPDATENORMALS", ntimes("handle", 1), None, "any"),
    ("COUNTTRIANGLES", ntimes("handle", 1), "int", "any"),
    ("COUNTVERTICES", ntimes("handle", 1), "int", "any"),
    ("VERTEXNX", ["handle", "int"], "float", "any"),
    ("VERTEXNY", ["handle", "int"], "float", "any"),
    ("VERTEXNZ", ["handle", "int"], "float", "any"),
    ("VERTEXU", ["handle", "int"], "float", "any"),
    ("VERTEXV", ["handle", "int"], "float", "any"),
    ("MESHWIDTH", ntimes("handle", 1), "float", "any"),
    ("MESHHEIGHT", ntimes("handle", 1), "float", "any"),
    ("MESHDEPTH", ntimes("handle", 1), "float", "any"),
    # brush
    ("LOADBRUSH", ntimes("string", 1), "handle", "any"),
    ("FREEBRUSH", ntimes("handle", 1), None, "any"),
    ("BRUSHCOLOR", ["handle", "int", "int", "int"], None, "any"),
    ("BRUSHALPHA", ["handle", "float"], None, "any"),
    ("BRUSHBLEND", ["handle", "int"], None, "any"),
    ("GETENTITYBRUSH", ntimes("handle", 1), "handle", "any"),
    ("GETSURFACEBRUSH", ntimes("handle", 1), "handle", "any"),
    ("PAINTSURFACE", ["handle", "handle"], None, "any"),
    # terrain
    ("LOADTERRAIN", ntimes("string", 1), "handle", "any"),
    ("TERRAINHEIGHT", ["handle", "float", "float"], "float", "any"),
    ("TERRAINSIZE", ntimes("handle", 1), "int", "any"),
    ("TERRAINDETAIL", ["handle", "int", "int"], None, "any"),
    ("TERRAINSHADING", ["handle", "int"], None, "any"),
    ("TERRAINX", ["handle", "float", "float", "float"], "float", "any"),
    ("TERRAINZ", ["handle", "float", "float", "float"], "float", "any"),
    ("MODIFYTERRAIN", ["handle", "int", "int", "float"], None, "any"),
    # animated texture
    ("LOADANIMTEXTURE", ["string", "int", "int", "int", "int", "int"], "handle", "any"),
    ("TEXTURENAME", ntimes("handle", 1), "string", "any"),
    ("TEXTURECOORDS", ["handle", "int"], None, "any"),
    ("POSITIONTEXTURE", ["handle", "float", "float"], None, "any"),
    ("SCALETEXTURE", ["handle", "float", "float"], None, "any"),
    ("ROTATETEXTURE", ["handle", "float"], None, "any"),
    # picking
    ("LINEPICK", ["float", "float", "float", "float", "float", "float", "float"], "handle", "any"),
    ("PICKEDENTITY", [], "handle", "any"),
    ("PICKEDX", [], "float", "any"),
    ("PICKEDY", [], "float", "any"),
    ("PICKEDZ", [], "float", "any"),
    ("PICKEDNX", [], "float", "any"),
    ("PICKEDNY", [], "float", "any"),
    ("PICKEDNZ", [], "float", "any"),
    ("PICKEDDISTANCE", [], "float", "any"),
    ("PICKEDSURFACE", [], "handle", "any"),
    ("PICKEDTRIANGLE", [], "int", "any"),
    # collision
    ("COLLISIONENTITY", ["handle", "int"], "handle", "any"),
    ("COLLISIONX", ["handle", "int"], "float", "any"),
    ("COLLISIONZ", ["handle", "int"], "float", "any"),
    ("SCALEENTITY", ["handle", "float", "float", "float"], None, "any"),
    ("ROTENT", ["handle", "float", "float", "float"], None, "any"),
    # entity extended
    ("ENTITY.SETCULLMODE", ["handle", "int"], None, "any"),
    ("ENTITY.SETTAG", ["handle", "string"], None, "any"),
    ("ENTITY.TAG", ntimes("handle", 1), "string", "any"),
    ("ENTITY.SETHEALTH", ["handle", "float"], None, "any"),
    ("ENTITY.DAMAGE", ["handle", "float"], None, "any"),
    ("ENTITY.ISALIVE", ntimes("handle", 1), "bool", "any"),
    ("ENTITY.CUTJUMP", ntimes("handle", 1), None, "any"),
    ("ENTITY.ISWALLSLIDING", ntimes("handle", 1), "bool", "any"),
    ("ENTITY.WASGROUNDED", ntimes("handle", 1), "bool", "any"),
    ("ENTITY.SETGRAVITY", ["handle", "float"], None, "any"),
    ("ENTITY.SETGRAVITYSCALE", ["handle", "float"], None, "any"),
    ("ENTITY.ADDTRAIL", ["handle", "int"], None, "any"),
    ("ENTITY.ADDWOBBLE", ["handle", "float", "float"], None, "any"),
    ("ENTITY.MAGNETTO", ["handle", "float", "float", "float", "float"], None, "any"),
    ("ENTITY.ONDEATHDROP", ["handle", "string"], None, "any"),
    ("ENTITY.NAVTO", ["handle", "float", "float", "float"], None, "any"),
    ("ENTITY.COLLIDED", ["handle", "int"], "bool", "any"),
    ("ENTITY.COLLISIONOTHER", ["handle", "int"], "handle", "any"),
    ("ENTITY.FLOOR", ntimes("handle", 1), "float", "any"),
    ("ENTITY.CREATECONE", ["int", "int", "int", "int"], "handle", "any"),
    ("ENTITY.MAKEBOX", ntimes("float", 3) + ntimes("int", 3), "handle", "any"),
    ("ENTITY.MAKECUBE", ntimes("float", 3) + ntimes("int", 3), "handle", "any"),
    ("ENTITY.MAKECYLINDER", ["int"] + ntimes("int", 3), "handle", "any"),
    ("ENTITY.MAKEPLANE", ntimes("int", 4), "handle", "any"),
    ("ENTITY.MAKESPHERE", ["int"] + ntimes("int", 3), "handle", "any"),
    ("ENTITY.MAKESPRITE", [], "handle", "any"),
    ("ENTITY.MAKEMESH", [], "handle", "any"),
    ("ENTITY.MAKEENTITY", [], "handle", "any"),
    ("ENTITY.MAKESURFACE", ["handle", "handle"], "handle", "any"),
    ("ENTITYREF.ISGROUNDED", ntimes("handle", 1), "bool", "any"),
    ("ENTITYREF.JUMP", ["handle", "float"], None, "any"),
    ("ENTITYREF.NAVUPDATE", ntimes("handle", 1), None, "any"),
    ("ENT.ISALIVE", ntimes("handle", 1), "bool", "any"),
    ("ENT.NAVTO", ["handle", "float", "float", "float"], None, "any"),
    ("ENT.SET_HP", ["handle", "float"], None, "any"),
    ("ENT.GET_NEAREST", ["handle", "int"], "handle", "any"),
    ("ENT.GETNEAREST", ["handle", "int"], "handle", "any"),
    ("ENTHIT", ["handle", "int"], "bool", "any"),
    ("ENTITYANIMATETOWARD", ["handle", "int", "float"], None, "any"),
    ("ENTPITCH", ntimes("handle", 1), "float", "any"),
    ("ENTYAW", ntimes("handle", 1), "float", "any"),
    ("ENTROLL", ntimes("handle", 1), "float", "any"),
    ("ENTP", ntimes("handle", 1), "float", "any"),
    ("ENTW", ntimes("handle", 1), "float", "any"),
    ("ENTR", ntimes("handle", 1), "float", "any"),
    # last 2 missing entity blitz
    ("APPLYENTITYFORCE", ["handle", "float", "float", "float"], None, "any"),
    ("APPLYENTITYTORQUE", ["handle", "float", "float", "float"], None, "any"),
]
