"""Input, mouse, keyboard, joystick, gamepad, and action-map manifest entries.

Covers: INPUT.*, MOUSE.*, KEY.*, JOY*, GAMEPAD.*, ACTION.*, AXIS.*,
        FLUSH*, WAIT*, GETKEY, GETJOY, HIDEPOINTER, SHOWPOINTER.
Arities verified from runtime/input source.
"""

from .helpers import ntimes

ENTRIES = [
    # --- input ---
    ("INPUT.CHARPRESSED", [], "int", "any"),
    ("INPUT.GETGAMEPADAXISVALUE", ntimes("int", 2), "float", "any"),
    ("INPUT.ISGAMEPADAVAILABLE", ntimes("int", 1), "bool", "any"),
    ("INPUT.MOUSEDELTAX", [], "float", "any"),
    ("INPUT.MOUSEDELTAY", [], "float", "any"),
    ("INPUT.MOUSEPRESSED", ntimes("int", 1), "bool", "any"),
    ("INPUT.MOUSERELEASED", ntimes("int", 1), "bool", "any"),
    ("INPUT.MOUSEWHEELMOVE", [], "float", "any"),
    ("INPUT.SETMOUSEPOS", ntimes("int", 2), None, "any"),
    ("INPUT.LOCKMOUSE", ntimes("bool", 1), None, "any"),
    # --- mouse ---
    ("MOUSE.X", [], "int", "any"),
    ("MOUSE.Y", [], "int", "any"),
    ("MOUSE.POSX", [], "int", "any"),
    ("MOUSE.POSY", [], "int", "any"),
    ("MOUSE.DOWN", ntimes("int", 1), "bool", "any"),
    ("MOUSE.PRESSED", ntimes("int", 1), "bool", "any"),
    ("MOUSE.RELEASED", ntimes("int", 1), "bool", "any"),
    ("MOUSE.DY", [], "float", "any"),
    ("MOUSE.WHEEL", [], "float", "any"),
    ("MOUSE.SETPOS", ntimes("int", 2), None, "any"),
    ("MOUSE.HIDE", [], None, "any"),
    ("MOUSE.SHOW", [], None, "any"),
    ("MOUSE.ENABLE", [], None, "any"),
    ("MOUSE.DISABLE", [], None, "any"),
    ("MOUSEDOWN", ntimes("int", 1), "bool", "any"),
    ("MOVEMOUSE", ntimes("int", 2), None, "any"),
    ("HIDEPOINTER", [], None, "any"),
    ("SHOWPOINTER", [], None, "any"),
    # --- input extended ---
    ("FLUSHKEYS", [], None, "any"),
    ("FLUSHMOUSE", [], None, "any"),
    ("WAITKEY", [], "int", "any"),
    ("WAITMOUSE", [], "int", "any"),
    ("GETKEY", [], "int", "any"),
    ("GETJOY", [], "int", "any"),
    ("KEY.HIT", ntimes("int", 1), "bool", "any"),
    ("KEY.UP", ntimes("int", 1), "bool", "any"),
    ("JOYDOWN", ntimes("int", 1), "bool", "any"),
    ("JOYHIT", ntimes("int", 1), "bool", "any"),
    ("JOYHAT", [], "int", "any"),
    ("JOYX", [], "float", "any"),
    ("JOYY", [], "float", "any"),
    ("JOYZ", [], "float", "any"),
    ("JOYU", [], "float", "any"),
    ("JOYV", [], "float", "any"),
    ("JOYPITCH", [], "float", "any"),
    ("JOYYAW", [], "float", "any"),
    ("JOYROLL", [], "float", "any"),
    ("JOYXDIR", [], "int", "any"),
    ("JOYYDIR", [], "int", "any"),
    ("GAMEPAD", [], "bool", "any"),
    ("GAMEPAD.AXIS", ntimes("int", 2), "float", "any"),
    ("GAMEPAD.BUTTON", ntimes("int", 2), "bool", "any"),
    ("ACTION.DOWN", ntimes("string", 1), "bool", "any"),
    ("ACTION.PRESSED", ntimes("string", 1), "bool", "any"),
    ("ACTION.RELEASED", ntimes("string", 1), "bool", "any"),
    ("ACTION.VALUE", ntimes("string", 1), "float", "any"),
    ("ACTION.MAPKEY", ["string", "int"], None, "any"),
    ("ACTION.MAPJOY", ["string", "int", "int"], None, "any"),
    ("ACTION.MAPMOUSE", ["string", "int"], None, "any"),
    ("ACTION.MAPAXIS", ["string", "int", "int"], None, "any"),
    ("ACTION.RESET", [], None, "any"),
    ("AXIS.DPADY", ntimes("int", 1), "float", "any"),
]
