"""Miscellaneous / global manifest entries.

Covers: easing functions, color constants & helpers, collision helpers,
        NOISE.*, IMAGE.*, GAME.*, PLAYER.*, CHAR.*, NET.*, ENET.*,
        TIME.*, DEBUG.*, CURSOR.*, UTIL.*, legacy draw globals (PLOT, LINE,
        RECT, TEXT), sprite globals, game-flow helpers, system queries,
        and MATH.CHANCE / MATH.RANGE.
Arities verified from runtime source.
"""

from .helpers import ntimes

ENTRIES = [
    # --- easing (global functions) ---
    ("EASEIN", ntimes("float", 3), "float", "any"),
    ("EASEOUT", ntimes("float", 3), "float", "any"),
    ("EASEINOUT", ntimes("float", 3), "float", "any"),
    ("EASEIN3", ntimes("float", 3), "float", "any"),
    ("EASEOUT3", ntimes("float", 3), "float", "any"),
    ("EASEINOUT3", ntimes("float", 3), "float", "any"),
    ("EASEINSINE", ntimes("float", 3), "float", "any"),
    ("EASEOUTSINE", ntimes("float", 3), "float", "any"),
    ("EASEINOUTSINE", ntimes("float", 3), "float", "any"),
    ("EASEINBACK", ntimes("float", 3), "float", "any"),
    ("EASEOUTBACK", ntimes("float", 3), "float", "any"),
    ("EASEINELASTIC", ntimes("float", 3), "float", "any"),
    ("EASEOUTELASTIC", ntimes("float", 3), "float", "any"),
    ("EASEINBOUNCE", ntimes("float", 3), "float", "any"),
    ("EASEOUTBOUNCE", ntimes("float", 3), "float", "any"),
    ("EASELERP", ntimes("float", 3), "float", "any"),
    # --- color constants and helpers ---
    ("COL_RED", [], "int", "any"),
    ("COL_GREEN", [], "int", "any"),
    ("COL_BLUE", [], "int", "any"),
    ("COL_WHITE", [], "int", "any"),
    ("COL_BLACK", [], "int", "any"),
    ("COL_YELLOW", [], "int", "any"),
    ("COL_ORANGE", [], "int", "any"),
    ("COL_MAGENTA", [], "int", "any"),
    ("COL_CYAN", [], "int", "any"),
    ("COL_GRAY", [], "int", "any"),
    ("COL_DARKGRAY", [], "int", "any"),
    ("COL_LIGHTGRAY", [], "int", "any"),
    ("COL_TRANSPARENT", [], "int", "any"),
    ("RGB", ntimes("int", 3), "int", "any"),
    ("RGBA", ntimes("int", 4), "int", "any"),
    ("ARGB", ntimes("int", 4), "int", "any"),
    ("RGBR", ntimes("int", 1), "int", "any"),
    ("RGBG", ntimes("int", 1), "int", "any"),
    ("RGBB", ntimes("int", 1), "int", "any"),
    ("RGBFADE", ["int", "float"], "int", "any"),
    ("RGBBRIGHTEN", ["int", "float"], "int", "any"),
    ("RGBDARKEN", ["int", "float"], "int", "any"),
    ("RGBMIX", ["int", "int", "float"], "int", "any"),
    # --- collision helpers (global) ---
    ("AABBCOLLIDE", ntimes("float", 12), "bool", "any"),
    ("BOXCOLLIDE", ntimes("float", 12), "bool", "any"),
    ("CIRCLECOLLIDE", ntimes("float", 6), "bool", "any"),
    ("CIRCLEBOXCOLLIDE", ntimes("float", 7), "bool", "any"),
    ("SPHEREBOXCOLLIDE", ntimes("float", 9), "bool", "any"),
    ("LINECOLLIDE", ntimes("float", 8), "bool", "any"),
    ("POINTINCIRCLE", ntimes("float", 5), "bool", "any"),
    ("POINTINBOX", ntimes("float", 6), "bool", "any"),
    ("POINTINAABB", ntimes("float", 9), "bool", "any"),
    ("POINTONLINE", ntimes("float", 6), "bool", "any"),
    ("POINTDIR2D", ntimes("float", 4), "float", "any"),
    ("POINTDIR3D", ntimes("float", 6), "float", "any"),
    ("DISTANCE2D", ntimes("float", 4), "float", "any"),
    ("DISTANCE3D", ntimes("float", 6), "float", "any"),
    ("DISTANCESQ2D", ntimes("float", 4), "float", "any"),
    ("DISTANCESQ3D", ntimes("float", 6), "float", "any"),
    # --- misc legacy / global ---
    ("APPROACH", ntimes("float", 3), "float", "any"),
    ("OSCILLATE", ntimes("float", 3), "float", "any"),
    ("NEWXVALUE", ntimes("float", 3), "float", "any"),
    ("NEWYVALUE", ntimes("float", 3), "float", "any"),
    ("NEWZVALUE", ntimes("float", 3), "float", "any"),
    ("WRAPVALUE", ntimes("float", 1), "float", "any"),
    ("PLOT", ntimes("int", 6), None, "rendering"),
    ("LINE", ntimes("int", 8), None, "rendering"),
    ("RECT", ntimes("int", 8), None, "rendering"),
    ("TEXT", ["int", "int", "string"], None, "rendering"),
    ("SPRITE", ntimes("string", 1), "handle", "any"),
    ("SPRITECOLOR", ["handle", "int", "int", "int", "int"], None, "any"),
    ("SPRITEALPHA", ["handle", "float"], None, "any"),
    ("SPRITEHIT", ["handle", "handle"], "bool", "any"),
    ("SPRITEIMAGE", ["handle", "handle"], None, "any"),
    ("MOVESPRITE", ["handle", "float", "float"], None, "any"),
    ("CLEAR", [], None, "rendering"),
    ("ENDGAME", [], None, "any"),
    ("FINISH", [], None, "any"),
    ("GAMEPAUSE", [], None, "any"),
    ("PAUSEGAME", [], None, "any"),
    ("RESUMEGAME", [], None, "any"),
    ("ELAPSED", [], "float", "any"),
    ("DELTATIME", [], "float", "any"),
    ("FRAMECOUNT", [], "int", "any"),
    ("SEEDRND", ntimes("int", 1), None, "any"),
    ("RNDRANGE", ntimes("float", 2), "float", "any"),
    ("RANDOMELEMENT", ntimes("handle", 1), "any", "any"),
    ("SHUFFLE", ntimes("handle", 1), None, "any"),
    ("WEIGHTEDRND", ntimes("handle", 1), "int", "any"),
    ("PERLIN", ntimes("float", 2), "float", "any"),
    ("SIMPLEX", ntimes("float", 2), "float", "any"),
    ("VORONOI", ntimes("float", 2), "float", "any"),
    ("FBMNOISE", ntimes("float", 3), "float", "any"),
    ("HASHINT", ntimes("int", 1), "int", "any"),
    ("HASHFLOAT", ntimes("float", 1), "float", "any"),
    ("FORMATINT", ["int", "int"], "string", "any"),
    ("FORMATSCORE", ntimes("int", 1), "string", "any"),
    ("FORMATTIME", ntimes("float", 1), "string", "any"),
    ("FORMATTIME2", ntimes("float", 1), "string", "any"),
    ("CURRENTDATE", [], "string", "any"),
    ("CURRENTTIME", [], "string", "any"),
    ("GPUNAME", [], "string", "any"),
    ("GRAPHICSWIDTH", [], "int", "any"),
    ("GRAPHICSHEIGHT", [], "int", "any"),
    ("GRAPHICSDEPTH", [], "int", "any"),
    ("SYSTEMPROPERTY", ntimes("string", 1), "string", "any"),
    ("AVAILVIDMEM", [], "int", "any"),
    ("TOTALVIDMEM", [], "int", "any"),
    # --- time extended ---
    ("TIME.MILLIS", [], "int", "any"),
    ("TIME.UPDATE", [], None, "any"),
    ("TIME.GETFPS", [], "float", "any"),
    ("TIMEMS", [], "int", "any"),
    # --- debug ---
    ("DEBUG.ENABLE", [], None, "any"),
    ("DEBUG.DISABLE", [], None, "any"),
    ("DEBUG.ISENABLED", [], "bool", "any"),
    # --- cursor ---
    ("CURSOR.ISENABLED", [], "bool", "any"),
    # --- noise create ---
    ("NOISE.CREATEPERLIN", [], "handle", "any"),
    ("NOISE.CREATESIMPLEX", [], "handle", "any"),
    ("NOISE.CREATECELLULAR", [], "handle", "any"),
    ("NOISE.CREATEFRACTAL", [], "handle", "any"),
    ("NOISE.CREATEDOMAINWARP", [], "handle", "any"),
    # --- player extended ---
    ("PLAYER.GETVX", ntimes("handle", 1), "float", "any"),
    ("PLAYER.GETVY", ntimes("handle", 1), "float", "any"),
    ("PLAYER.GETVZ", ntimes("handle", 1), "float", "any"),
    ("PLAYER.ISMOVING", ntimes("handle", 1), "bool", "any"),
    ("PLAYER.UPDATE", ntimes("handle", 1), None, "any"),
    ("PLAYER2D.SETPOSITION", ["handle", "float", "float"], None, "any"),
    # --- char controller ---
    ("CHAR.GETCAPSULEHEIGHT", ntimes("handle", 1), "float", "any"),
    ("CHAR.GETCAPSULERADIUS", ntimes("handle", 1), "float", "any"),
    ("CHAR.GETGRAVITY", ntimes("handle", 1), "float", "any"),
    ("CHAR.GETGROUNDED", ntimes("handle", 1), "bool", "any"),
    ("CHAR.GETPITCH", ntimes("handle", 1), "float", "any"),
    ("CHAR.GETROLL", ntimes("handle", 1), "float", "any"),
    ("CHAR.GETSHAPETYPE", ntimes("handle", 1), "int", "any"),
    ("CHAR.GETX", ntimes("handle", 1), "float", "any"),
    ("CHAR.GETY", ntimes("handle", 1), "float", "any"),
    ("CHAR.GETYAW", ntimes("handle", 1), "float", "any"),
    ("CHAR.GETZ", ntimes("handle", 1), "float", "any"),
    ("CHAR.GETVX", ntimes("handle", 1), "float", "any"),
    ("CHAR.GETVY", ntimes("handle", 1), "float", "any"),
    ("CHAR.GETVZ", ntimes("handle", 1), "float", "any"),
    ("CHAR.UPDATE", ntimes("handle", 1), None, "any"),
    # --- net / enet ---
    ("NET.MAKESERVER", ntimes("int", 1), "handle", "any"),
    ("NET.MAKECLIENT", [], "handle", "any"),
    ("LISTEN", ntimes("int", 1), "handle", "any"),
    ("CONNECT", ntimes("string", 1), "handle", "any"),
    ("SERVICENET", ntimes("handle", 1), None, "any"),
    ("NETMSG$", ntimes("handle", 1), "string", "any"),
    ("NET_RELIABLE", [], "int", "any"),
    ("NET_UNRELIABLE", [], "int", "any"),
    ("ENET.INITIALIZE", [], None, "any"),
    ("ENET.DEINITIALIZE", [], None, "any"),
    ("ENET.CREATEHOST", ntimes("any", 4), "handle", "any"),
    ("ENET.MAKEHOST", ntimes("any", 4), "handle", "any"),
    ("ENET.HOSTSERVICE", ["handle", "int"], "handle", "any"),
    ("ENET.HOSTBROADCAST", ["handle", "int", "string"], None, "any"),
    ("ENET.PEERSEND", ["handle", "int", "string"], None, "any"),
    ("ENET.PEERPING", ntimes("handle", 1), None, "any"),
    # --- misc game helpers ---
    ("GAME.", [], None, "any"),   # empty key observed in runtime
    ("GAME.BURSTSPAWN", ["handle", "int", "float", "float", "float"], None, "any"),
    ("GAME.DEBUGRECT", ntimes("int", 8), None, "rendering"),
    ("GAME.DRAWSCREENFLASH", [], None, "rendering"),
    ("GAME.SCREENFLASH", ntimes("int", 4), None, "rendering"),
    ("GAME.ISCURSORONSCREEN", [], "bool", "any"),
    ("GAME.ISGAMEPADAVAILABLE", ntimes("int", 1), "bool", "any"),
    ("GAME.GETGAMEPADNAME", ntimes("int", 1), "string", "any"),
    ("GAME.SETMASTERVOLUME", ntimes("float", 1), None, "any"),
    ("GAME.GETMASTERVOLUME", [], "float", "any"),
    ("GAME.SETAESTHETIC", ntimes("int", 1), None, "any"),
    ("GAME.MAKEFLOATARRAY", ntimes("int", 1), "handle", "any"),
    ("GAME.SPRITETILEBRIDGE", ntimes("any", 4), None, "any"),
    # --- image ---
    ("IMAGE.CREATEBLANK", ntimes("int", 2), "handle", "any"),
    ("IMAGE.CREATECOPY", ntimes("handle", 1), "handle", "any"),
    ("IMAGE.CREATETEXT", ["int", "int", "string", "int", "int", "int", "int", "int"], "handle", "any"),
    # --- util ---
    ("UTIL.COPYFILE", ntimes("string", 2), None, "any"),
    ("UTIL.DELETEDIR", ntimes("string", 1), None, "any"),
    ("UTIL.DELETEFILE", ntimes("string", 1), None, "any"),
    ("UTIL.GETDIR", [], "string", "any"),
    ("UTIL.GETDIRS", ntimes("string", 1), "string", "any"),
    ("UTIL.MOVEFILE", ntimes("string", 2), None, "any"),
    ("UTIL.RENAMEFILE", ntimes("string", 2), None, "any"),
    # --- math extended (global aliases) ---
    ("MATH.CHANCE", ntimes("float", 1), "bool", "any"),
    ("MATH.RANGE", ntimes("float", 2), "float", "any"),
    # --- misc string-returning / debug ---
    ("PRINTAT", ["int", "int", "string"], None, "any"),
    ("PRINTCOLOR", ["string", "int", "int", "int", "int"], None, "any"),
    ("TRACE", ["any"], None, "any"),
    ("THROW", ntimes("string", 1), None, "any"),
    ("ERR", [], "int", "any"),
    ("ERRMSG$", [], "string", "any"),
    ("ERRFILE$", [], "string", "any"),
    ("ERRLINE", [], "int", "any"),
    ("DUMP", ntimes("any", 1), None, "any"),
    ("UPDW", [], None, "any"),
    # --- tween ---
    ("TWEEN.FREE", ntimes("handle", 1), None, "any"),
]
