"""Ray-intersection query manifest entries.

Covers: RAY.HITBOX_*, RAY.HITSPHERE_*, RAY.HITMESH_*, RAY.HITMODEL_*,
        RAY.HITPLANE_*, RAY.HITTRIANGLE_*, RAY.INTERSECTSMODEL_*.
All are zero-arg result queries (state is set by a prior ray-cast call).
Arities verified from runtime/raycast source.
"""

ENTRIES = [
    ("RAY.HITBOX_HIT", [], "bool", "any"),
    ("RAY.HITBOX_DISTANCE", [], "float", "any"),
    ("RAY.HITBOX_POINTX", [], "float", "any"),
    ("RAY.HITBOX_POINTY", [], "float", "any"),
    ("RAY.HITBOX_POINTZ", [], "float", "any"),
    ("RAY.HITBOX_NORMALX", [], "float", "any"),
    ("RAY.HITBOX_NORMALY", [], "float", "any"),
    ("RAY.HITBOX_NORMALZ", [], "float", "any"),
    ("RAY.HITSPHERE_HIT", [], "bool", "any"),
    ("RAY.HITSPHERE_DISTANCE", [], "float", "any"),
    ("RAY.HITSPHERE_POINTX", [], "float", "any"),
    ("RAY.HITSPHERE_POINTY", [], "float", "any"),
    ("RAY.HITSPHERE_POINTZ", [], "float", "any"),
    ("RAY.HITSPHERE_NORMALX", [], "float", "any"),
    ("RAY.HITSPHERE_NORMALY", [], "float", "any"),
    ("RAY.HITSPHERE_NORMALZ", [], "float", "any"),
    ("RAY.HITMESH_HIT", [], "bool", "any"),
    ("RAY.HITMESH_DISTANCE", [], "float", "any"),
    ("RAY.HITMESH_POINTX", [], "float", "any"),
    ("RAY.HITMESH_POINTY", [], "float", "any"),
    ("RAY.HITMESH_POINTZ", [], "float", "any"),
    ("RAY.HITMESH_NORMALX", [], "float", "any"),
    ("RAY.HITMESH_NORMALY", [], "float", "any"),
    ("RAY.HITMESH_NORMALZ", [], "float", "any"),
    ("RAY.HITMODEL_HIT", [], "bool", "any"),
    ("RAY.HITMODEL_DISTANCE", [], "float", "any"),
    ("RAY.HITMODEL_POINTX", [], "float", "any"),
    ("RAY.HITMODEL_POINTY", [], "float", "any"),
    ("RAY.HITMODEL_POINTZ", [], "float", "any"),
    ("RAY.HITMODEL_NORMALX", [], "float", "any"),
    ("RAY.HITMODEL_NORMALY", [], "float", "any"),
    ("RAY.HITMODEL_NORMALZ", [], "float", "any"),
    ("RAY.HITPLANE_HIT", [], "bool", "any"),
    ("RAY.HITPLANE_DISTANCE", [], "float", "any"),
    ("RAY.HITPLANE_POINTX", [], "float", "any"),
    ("RAY.HITPLANE_POINTY", [], "float", "any"),
    ("RAY.HITPLANE_POINTZ", [], "float", "any"),
    ("RAY.HITPLANE_NORMALX", [], "float", "any"),
    ("RAY.HITPLANE_NORMALY", [], "float", "any"),
    ("RAY.HITPLANE_NORMALZ", [], "float", "any"),
    ("RAY.HITTRIANGLE_HIT", [], "bool", "any"),
    ("RAY.HITTRIANGLE_DISTANCE", [], "float", "any"),
    ("RAY.HITTRIANGLE_POINTX", [], "float", "any"),
    ("RAY.HITTRIANGLE_POINTY", [], "float", "any"),
    ("RAY.HITTRIANGLE_POINTZ", [], "float", "any"),
    ("RAY.HITTRIANGLE_NORMALX", [], "float", "any"),
    ("RAY.HITTRIANGLE_NORMALY", [], "float", "any"),
    ("RAY.HITTRIANGLE_NORMALZ", [], "float", "any"),
    ("RAY.INTERSECTSMODEL_HIT", [], "bool", "any"),
    ("RAY.INTERSECTSMODEL_DISTANCE", [], "float", "any"),
    ("RAY.INTERSECTSMODEL_POINTX", [], "float", "any"),
    ("RAY.INTERSECTSMODEL_POINTY", [], "float", "any"),
    ("RAY.INTERSECTSMODEL_POINTZ", [], "float", "any"),
    ("RAY.INTERSECTSMODEL_NORMALX", [], "float", "any"),
    ("RAY.INTERSECTSMODEL_NORMALY", [], "float", "any"),
    ("RAY.INTERSECTSMODEL_NORMALZ", [], "float", "any"),
]
