"""Rendering, window, texture, light, post-processing, and RAYLIB pass-through entries.

Covers: RENDER.*, WINDOW.*, TEXTURE.*, LIGHT.*, POST.*, EFFECT.*,
        SET* globals, RAYLIB.* low-level pass-through.
Arities verified from runtime/render, runtime/window, runtime/light source.
"""

from .helpers import ntimes

ENTRIES = [
    # --- texture ---
    (
        "TEXTURE.GENCHECKED",
        ntimes("int", 4) + ntimes("handle", 2),
        "handle",
        "any",
    ),
    ("TEXTURE.GENCOLOR", ntimes("int", 6), "handle", "any"),
    ("TEXTURE.GENGRADIENTH", ntimes("int", 2) + ntimes("handle", 2), "handle", "any"),
    ("TEXTURE.GENGRADIENTV", ntimes("int", 2) + ntimes("handle", 2), "handle", "any"),
    ("TEXTURE.HEIGHT", ntimes("handle", 1), "int", "any"),
    ("TEXTURE.SETFILTER", ["handle", "int"], None, "any"),
    ("TEXTURE.SETWRAP", ["handle", "int"], None, "any"),
    ("TEXTURE.UPDATE", ntimes("handle", 2), None, "any"),
    ("TEXTURE.WIDTH", ntimes("handle", 1), "int", "any"),
    # --- texture extended ---
    ("TEXTURE.LOADANIM", ["string", "int", "int"], "handle", "any"),
    ("TEXTURE.LOADASYNC", ntimes("string", 1), "handle", "any"),
    ("TEXTURE.ISLOADED", ntimes("handle", 1), "bool", "any"),
    ("TEXTURE.PLAY", ["handle", "int", "int", "bool"], None, "any"),
    ("TEXTURE.STOPANIM", ntimes("handle", 1), None, "any"),
    ("TEXTURE.SETFRAME", ["handle", "int"], None, "any"),
    ("TEXTURE.SETGRID", ["handle", "int", "int"], None, "any"),
    ("TEXTURE.SETUVSCROLL", ["handle", "float", "float"], None, "any"),
    ("TEXTURE.SETDISTORTION", ["handle", "float"], None, "any"),
    ("TEXTURE.TICKALL", ntimes("float", 1), None, "any"),
    # --- render extended ---
    ("RENDER.SET2DAMBIENT", ntimes("int", 4), None, "rendering"),
    ("RENDER.HEIGHT", [], "int", "rendering"),
    ("RENDER.WIDTH", [], "int", "rendering"),
    ("RENDER.SETPOSTPROCESS", ntimes("handle", 1), None, "rendering"),
    ("RENDER.BEGINFRAME", [], None, "rendering"),
    ("RENDER.ENDFRAME", [], None, "rendering"),
    ("RENDER.BEGINMODE2D", ntimes("handle", 1), None, "rendering"),
    ("RENDER.ENDMODE2D", [], None, "rendering"),
    ("RENDER.BEGINMODE3D", ntimes("handle", 1), None, "rendering"),
    ("RENDER.ENDMODE3D", [], None, "rendering"),
    ("RENDER.BEGINSHADER", ntimes("handle", 1), None, "rendering"),
    ("RENDER.ENDSHADER", [], None, "rendering"),
    ("RENDER.SETCULLFACE", ntimes("int", 1), None, "rendering"),
    ("RENDER.SETFPS", ntimes("int", 1), None, "rendering"),
    ("RENDER.SETIBLINTENSITY", ntimes("float", 1), None, "rendering"),
    ("RENDER.SETIBLSPLIT", ntimes("float", 1), None, "rendering"),
    ("RENDER.SETSKYBOX", ntimes("handle", 1), None, "rendering"),
    ("SETFPS", ntimes("int", 1), None, "any"),
    ("SETVSYNC", ntimes("bool", 1), None, "any"),
    ("SETVIEWPORT", ntimes("int", 4), None, "rendering"),
    ("SETORIGIN", ntimes("int", 2), None, "rendering"),
    ("SETBLOOM", ntimes("float", 1), None, "rendering"),
    ("SETCLEARCOLOR", ntimes("int", 3), None, "rendering"),
    ("SETCOLOR", ntimes("int", 4), None, "rendering"),
    ("SETALPHA", ntimes("float", 1), None, "rendering"),
    ("SETAMBIENT", ntimes("int", 3), None, "rendering"),
    ("SETFOG", ["int", "int", "int", "float", "float"], None, "rendering"),
    ("SETWIREFRAME", ntimes("bool", 1), None, "rendering"),
    ("SETCUBEFACE", ["handle", "int"], None, "rendering"),
    ("SETCUBEMODE", ["handle", "int"], None, "rendering"),
    # --- window ---
    ("WINDOW.GETFPS", [], "int", "any"),
    ("WINDOW.HEIGHT", [], "int", "any"),
    ("WINDOW.ISFULLSCREEN", [], "bool", "any"),
    ("WINDOW.ISRESIZED", [], "bool", "any"),
    ("WINDOW.TOGGLEFULLSCREEN", [], None, "any"),
    ("WINDOW.WIDTH", [], "int", "any"),
    ("WINDOW.DPISCALE", [], "float", "any"),
    ("WINDOWWIDTH", [], "int", "any"),
    ("WINDOWHEIGHT", [], "int", "any"),
    # --- post-processing ---
    ("POST.BLOOM", ntimes("float", 1), None, "rendering"),
    ("POST.CHROMATIC", ntimes("float", 1), None, "rendering"),
    ("POST.VIGNETTE", ntimes("float", 2), None, "rendering"),
    ("EFFECT.FXAA", ntimes("bool", 1), None, "rendering"),
    # --- light blitz compat ---
    ("LIGHTCONE", ["handle", "float", "float"], None, "rendering"),
    ("LIGHTPOINTAT", ["handle", "float", "float", "float"], None, "rendering"),
    ("LIGHTPOSITION", ["handle", "float", "float", "float"], None, "rendering"),
    ("LIGHT.MAKEDIRECTIONAL", ntimes("float", 6) + ntimes("int", 3), "handle", "rendering"),
    ("LIGHT.MAKEPOINT", ntimes("float", 3) + ntimes("int", 3), "handle", "rendering"),
    ("LIGHT.MAKESPOT", ntimes("float", 6) + ntimes("int", 3) + ntimes("float", 2), "handle", "rendering"),
    ("LIGHT.SETROT", ["handle", "float", "float", "float"], None, "rendering"),
    ("LIGHT.GETROT", ntimes("handle", 1), "handle", "rendering"),
    ("LIGHT.GETINTENSITY", ntimes("handle", 1), "float", "rendering"),
    # --- raylib low-level pass-through ---
    ("RAYLIB.INITWINDOW", ["int", "int", "string"], None, "any"),
    ("RAYLIB.CLOSEWINDOW", [], None, "any"),
    ("RAYLIB.WINDOWSHOULDCLOSE", [], "bool", "any"),
    ("RAYLIB.SETTARGETFPS", ntimes("int", 1), None, "any"),
    ("RAYLIB.GETFPS", [], "int", "any"),
    ("RAYLIB.GETTIME", [], "float", "any"),
    ("RAYLIB.BEGINFRAME", [], None, "rendering"),
    ("RAYLIB.ENDFRAME", [], None, "rendering"),
    ("RAYLIB.CLEARBACKGROUND", ntimes("int", 4), None, "rendering"),
    ("RAYLIB.DRAWRECTANGLE", ntimes("int", 8), None, "rendering"),
    ("RAYLIB.DRAWCIRCLE", ntimes("int", 7), None, "rendering"),
    ("RAYLIB.DRAWLINE3D", ntimes("float", 6) + ntimes("int", 4), None, "rendering"),
    ("RAYLIB.DRAWCUBE", ntimes("float", 7) + ntimes("int", 4), None, "rendering"),
    ("RAYLIB.DRAWSPHERE", ntimes("float", 4) + ntimes("int", 4), None, "rendering"),
    ("RAYLIB.DRAWTEXTURE", ["handle", "int", "int"] + ntimes("int", 4), None, "rendering"),
    ("RAYLIB.DRAWMODEL", ["handle", "float", "float", "float", "float"] + ntimes("int", 4), None, "rendering"),
    ("RAYLIB.DRAWFPS", ntimes("int", 2), None, "rendering"),
    ("RAYLIB.LOADTEXTURE", ntimes("string", 1), "handle", "any"),
    ("RAYLIB.UNLOADTEXTURE", ntimes("handle", 1), None, "any"),
    ("RAYLIB.LOADMODEL", ntimes("string", 1), "handle", "any"),
    ("RAYLIB.LOADSHADER", ntimes("string", 2), "handle", "any"),
    ("RAYLIB.BEGINSHADERMODE", ntimes("handle", 1), None, "rendering"),
    ("RAYLIB.ENDSHADERMODE", [], None, "rendering"),
    ("RAYLIB.ISKEYDOWN", ntimes("int", 1), "bool", "any"),
    ("RAYLIB.ISKEYPRESSED", ntimes("int", 1), "bool", "any"),
    ("RAYLIB.ISKEYRELEASED", ntimes("int", 1), "bool", "any"),
    ("RAYLIB.ISMOUSEBUTTONDOWN", ntimes("int", 1), "bool", "any"),
    ("RAYLIB.GETMOUSEX", [], "int", "any"),
    ("RAYLIB.GETMOUSEY", [], "int", "any"),
    ("RAYLIB.SETCAMERAMODE", ["handle", "int"], None, "any"),
    ("RAYLIB.UPDATECAMERA", ntimes("handle", 1), None, "any"),
    ("RAYLIB.GETFRAMEBUFFERWIDTH", [], "int", "any"),
    ("RAYLIB.GETFRAMEBUFFERHEIGHT", [], "int", "any"),
]
