"""World-object manifest entries: particles, culling, decals, water, terrain,
scatter/prop, spawner, trigger, level, mover, instance, navagent.

Arities verified from runtime source for each subsystem.
"""

from .helpers import ntimes

ENTRIES = [
    # --- cull ---
    ("CULL.SPHEREVISIBLE", ntimes("float", 4), "bool", "rendering"),
    ("CULL.AABBVISIBLE", ntimes("float", 6), "bool", "rendering"),
    ("CULL.POINTVISIBLE", ntimes("float", 3), "bool", "rendering"),
    ("CULL.DISTANCE", ntimes("float", 6), "float", "any"),
    ("CULL.DISTANCESQ", ntimes("float", 6), "float", "any"),
    ("CULL.INRANGE", ntimes("float", 7), "bool", "any"),
    ("CULL.SETMAXDISTANCE", ntimes("float", 1), None, "rendering"),
    ("CULL.GETMAXDISTANCE", [], "float", "rendering"),
    ("CULL.SETBACKFACECULLING", ntimes("bool", 1), None, "rendering"),
    ("CULL.BEHINDHORIZON", ntimes("float", 3), "bool", "rendering"),
    ("CULL.ISOCCLUDED", ntimes("float", 3), "bool", "rendering"),
    ("CULL.OCCLUDERADD", ntimes("float", 6), None, "rendering"),
    ("CULL.OCCLUDERCLEAR", [], None, "rendering"),
    ("CULL.OCCLUSIONENABLE", ntimes("bool", 1), None, "rendering"),
    ("CULL.BATCHSPHERE", ["handle", "float"], "handle", "rendering"),
    ("CULL.STATSTOTAL", [], "int", "rendering"),
    ("CULL.STATSVISIBLE", [], "int", "rendering"),
    ("CULL.STATSCULLED", [], "int", "rendering"),
    ("CULL.STATSFRUSTUMCULLED", [], "int", "rendering"),
    ("CULL.STATSDISTANCECULLED", [], "int", "rendering"),
    ("CULL.STATSHORIZONCULLED", [], "int", "rendering"),
    ("CULL.STATSOCCLUSIONCULLED", [], "int", "rendering"),
    ("CULL.STATSRESET", [], None, "rendering"),
    # --- particle (both 2d and 3d) ---
    ("PARTICLE.CREATE", [], "handle", "rendering"),
    ("PARTICLE.MAKE", [], "handle", "rendering"),
    ("PARTICLE.FREE", ntimes("handle", 1), None, "rendering"),
    ("PARTICLE.SETPOS", ["handle", "float", "float", "float"], None, "rendering"),
    ("PARTICLE.SETPOSITION", ["handle", "float", "float", "float"], None, "rendering"),
    ("PARTICLE.SETTEXTURE", ["handle", "handle"], None, "rendering"),
    ("PARTICLE.SETCOLOR", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("PARTICLE.SETCOLOREND", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("PARTICLE.SETSIZE", ["handle", "float"], None, "rendering"),
    ("PARTICLE.SETSTARTSIZE", ["handle", "float"], None, "rendering"),
    ("PARTICLE.SETENDSIZE", ["handle", "float"], None, "rendering"),
    ("PARTICLE.SETLIFETIME", ["handle", "float"], None, "rendering"),
    ("PARTICLE.SETSPEED", ["handle", "float"], None, "rendering"),
    ("PARTICLE.SETSPREAD", ["handle", "float"], None, "rendering"),
    ("PARTICLE.SETDIRECTION", ["handle", "float", "float", "float"], None, "rendering"),
    ("PARTICLE.SETVELOCITY", ["handle", "float", "float", "float"], None, "rendering"),
    ("PARTICLE.SETGRAVITY", ["handle", "float"], None, "rendering"),
    ("PARTICLE.SETEMITRATE", ["handle", "float"], None, "rendering"),
    ("PARTICLE.SETBURST", ["handle", "int"], None, "rendering"),
    ("PARTICLE.SETBILLBOARD", ["handle", "bool"], None, "rendering"),
    ("PARTICLE.PLAY", ntimes("handle", 1), None, "rendering"),
    ("PARTICLE.STOP", ntimes("handle", 1), None, "rendering"),
    ("PARTICLE.UPDATE", ["handle", "float"], None, "rendering"),
    ("PARTICLE.DRAW", ntimes("handle", 1), None, "rendering"),
    ("PARTICLE.COUNT", ntimes("handle", 1), "int", "rendering"),
    ("PARTICLE.ISALIVE", ntimes("handle", 1), "bool", "rendering"),
    ("PARTICLE.GETPOS", ntimes("handle", 1), "handle", "rendering"),
    ("PARTICLE.GETCOLOR", ntimes("handle", 1), "handle", "rendering"),
    ("PARTICLE.GETALPHA", ntimes("handle", 1), "float", "rendering"),
    ("PARTICLEEMITRATE", ["handle", "float"], None, "rendering"),
    ("PARTICLEVELOCITY", ["handle", "float", "float", "float"], None, "rendering"),
    # particle3d variants
    ("PARTICLE3D.CREATE", [], "handle", "rendering"),
    ("PARTICLE3D.MAKE", [], "handle", "rendering"),
    ("PARTICLE3D.FREE", ntimes("handle", 1), None, "rendering"),
    ("PARTICLE3D.SETPOS", ["handle", "float", "float", "float"], None, "rendering"),
    ("PARTICLE3D.SETPOSITION", ["handle", "float", "float", "float"], None, "rendering"),
    ("PARTICLE3D.SETTEXTURE", ["handle", "handle"], None, "rendering"),
    ("PARTICLE3D.SETCOLOR", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("PARTICLE3D.SETCOLOREND", ["handle", "int", "int", "int", "int"], None, "rendering"),
    ("PARTICLE3D.SETSIZE", ["handle", "float"], None, "rendering"),
    ("PARTICLE3D.SETSTARTSIZE", ["handle", "float"], None, "rendering"),
    ("PARTICLE3D.SETENDSIZE", ["handle", "float"], None, "rendering"),
    ("PARTICLE3D.SETLIFETIME", ["handle", "float"], None, "rendering"),
    ("PARTICLE3D.SETSPEED", ["handle", "float"], None, "rendering"),
    ("PARTICLE3D.SETSPREAD", ["handle", "float"], None, "rendering"),
    ("PARTICLE3D.SETDIRECTION", ["handle", "float", "float", "float"], None, "rendering"),
    ("PARTICLE3D.SETVELOCITY", ["handle", "float", "float", "float"], None, "rendering"),
    ("PARTICLE3D.SETGRAVITY", ["handle", "float"], None, "rendering"),
    ("PARTICLE3D.SETEMITRATE", ["handle", "float"], None, "rendering"),
    ("PARTICLE3D.SETBURST", ["handle", "int"], None, "rendering"),
    ("PARTICLE3D.SETBILLBOARD", ["handle", "bool"], None, "rendering"),
    ("PARTICLE3D.PLAY", ntimes("handle", 1), None, "rendering"),
    ("PARTICLE3D.STOP", ntimes("handle", 1), None, "rendering"),
    ("PARTICLE3D.UPDATE", ["handle", "float"], None, "rendering"),
    ("PARTICLE3D.DRAW", ntimes("handle", 1), None, "rendering"),
    ("PARTICLE3D.COUNT", ntimes("handle", 1), "int", "rendering"),
    ("PARTICLE3D.ISALIVE", ntimes("handle", 1), "bool", "rendering"),
    ("PARTICLE3D.GETPOS", ntimes("handle", 1), "handle", "rendering"),
    ("PARTICLE3D.GETCOLOR", ntimes("handle", 1), "handle", "rendering"),
    ("PARTICLE3D.GETALPHA", ntimes("handle", 1), "float", "rendering"),
    # --- decal ---
    ("DECAL.SETPOSITION", ["handle", "float", "float", "float"], None, "rendering"),
    ("DECAL.GETPOS", ntimes("handle", 1), "handle", "rendering"),
    ("DECAL.GETROT", ntimes("handle", 1), "handle", "rendering"),
    ("DECAL.GETSIZE", ntimes("handle", 1), "handle", "rendering"),
    # --- scatter / prop ---
    ("SCATTER.CREATE", ntimes("handle", 1), "handle", "any"),
    ("SCATTER.APPLY", ntimes("handle", 1), None, "any"),
    ("SCATTER.DRAWALL", [], None, "rendering"),
    ("SCATTER.FREE", ntimes("handle", 1), None, "any"),
    ("PROP.PLACE", ntimes("any", 4), "handle", "any"),
    ("PROP.DRAWALL", [], None, "rendering"),
    ("PROP.FREE", ntimes("handle", 1), None, "any"),
    # --- spawner ---
    ("SPAWNER.MAKE", ntimes("any", 4), "handle", "any"),
    # --- trigger ---
    ("TRIGGER.MAKEFROMENTITY", ntimes("handle", 1), "handle", "any"),
    ("TRIGGER.MAKEZONE", ntimes("float", 6), "handle", "any"),
    # --- water ---
    ("WATER.SHOW", ntimes("bool", 1), None, "rendering"),
    ("WATER.SETPOSITION", ntimes("float", 3), None, "rendering"),
    ("WATER.SETHEIGHT", ntimes("float", 1), None, "rendering"),
    ("WATER.AUTOPHYSICS", ntimes("bool", 1), None, "any"),
    # --- terrain extended ---
    ("TERRAIN.SETPOSITION", ntimes("float", 3), None, "rendering"),
    # --- level ---
    ("LEVEL.SETUP", ntimes("string", 1), None, "any"),
    # --- mover ---
    ("MOVER.FREE", ntimes("handle", 1), None, "any"),
    ("MOVER.LAND", ntimes("handle", 1), None, "any"),
    ("MOVER.MOVEREL", ["handle", "float", "float", "float"], None, "any"),
    # --- instance ---
    ("INSTANCE.SETPOSITION", ["handle", "float", "float", "float"], None, "any"),
    # --- navagent ---
    ("NAVAGENT.SETPOSITION", ["handle", "float", "float", "float"], None, "any"),
]
