package input

import (
	"moonbasic/runtime"
	"moonbasic/vm/value"
)

func (m *Module) Register(r runtime.Registrar) {
	// Core keyboard (raylib_cgo.go)
	r.Register("INPUT.KEYDOWN", "input", runtime.AdaptLegacy(func(args []value.Value) (value.Value, error) { return m.inKeyDown(args) }))
	r.Register("INPUT.KEYPRESSED", "input", runtime.AdaptLegacy(func(args []value.Value) (value.Value, error) { return m.inKeyPressed(args) }))
	r.Register("INPUT.KEYUP", "input", runtime.AdaptLegacy(func(args []value.Value) (value.Value, error) { return m.inKeyReleased(args) }))
	r.Register("INPUT.GETKEYNAME", "input", runtime.AdaptLegacy(m.inGetKeyName))
	r.Register("INPUT.GETINACTIVITY", "input", runtime.AdaptLegacy(m.inGetInactivity))

	// Movement & Axis
	r.Register("INPUT.MOVEMENT2D", "input", runtime.AdaptLegacy(m.movement2D))
	r.Register("INPUT.MOVEDIR", "input", runtime.AdaptLegacy(m.inputMoveDir))
	r.Register("INPUT.AXIS", "input", runtime.AdaptLegacy(m.inputAxis))
	r.Register("INPUT.AXISDEG", "input", runtime.AdaptLegacy(m.inputAxisDeg))
	r.Register("INPUT.ORBIT", "input", runtime.AdaptLegacy(m.inputAxisDeg))
	r.Register("AXIS.DPADY", "input", runtime.AdaptLegacy(m.axisDPadY))

	// Mouse Facade (facade_cgo.go)
	r.Register("MOUSE.DX", "input", runtime.AdaptLegacy(m.mouseDX))
	r.Register("MOUSE.DY", "input", runtime.AdaptLegacy(m.mouseDY))
	r.Register("MOUSE.WHEEL", "input", runtime.AdaptLegacy(m.mouseWheel))
	r.Register("MOUSE.DOWN", "input", runtime.AdaptLegacy(m.mouseDown))
	r.Register("MOUSE.PRESSED", "input", runtime.AdaptLegacy(m.mousePressed))
	r.Register("MOUSE.RELEASED", "input", runtime.AdaptLegacy(m.mouseReleased))
	r.Register("MOUSE", "input", runtime.AdaptLegacy(m.makeMouse))
	r.Register("MOUSEHIT", "input", runtime.AdaptLegacy(m.mouseHitGlobal))
	r.Register("MOUSEX", "input", runtime.AdaptLegacy(m.mouseXGlobal))
	r.Register("MOUSEY", "input", runtime.AdaptLegacy(m.mouseYGlobal))

	// Key Facade
	r.Register("KEY.DOWN", "input", runtime.AdaptLegacy(m.keyDown))
	r.Register("KEY.HIT", "input", runtime.AdaptLegacy(m.keyHit))
	r.Register("KEY.UP", "input", runtime.AdaptLegacy(m.keyUp))
	r.Register("KEY", "input", runtime.AdaptLegacy(m.makeKey))

	// Gamepad Facade
	r.Register("GAMEPAD.AXIS", "input", runtime.AdaptLegacy(m.gpAxis))
	r.Register("GAMEPAD.BUTTON", "input", runtime.AdaptLegacy(m.gpButton))
	r.Register("GAMEPAD", "input", runtime.AdaptLegacy(m.makeGamepad))

	// Mouse Extra (mouse_extra_cgo.go)
	r.Register("MOUSE.X", "input", runtime.AdaptLegacy(m.inMouseX))
	r.Register("MOUSE.Y", "input", runtime.AdaptLegacy(m.inMouseY))
	r.Register("MOUSE.POSX", "input", runtime.AdaptLegacy(m.inMouseX))
	r.Register("MOUSE.POSY", "input", runtime.AdaptLegacy(m.inMouseY))
	r.Register("MOUSE.SETPOS", "input", runtime.AdaptLegacy(m.inSetMousePos))
	r.Register("MOUSE.SETPOSITION", "input", runtime.AdaptLegacy(m.inSetMousePos))
	r.Register("MOUSE.SHOW", "input", runtime.AdaptLegacy(m.cursorShow))
	r.Register("MOUSE.HIDE", "input", runtime.AdaptLegacy(m.cursorHide))
	r.Register("MOUSE.ENABLE", "input", runtime.AdaptLegacy(m.cursorEnable))
	r.Register("MOUSE.DISABLE", "input", runtime.AdaptLegacy(m.cursorDisable))

	r.Register("INPUT.MOUSEPRESSED", "input", runtime.AdaptLegacy(m.inMousePressed))
	r.Register("INPUT.MOUSERELEASED", "input", runtime.AdaptLegacy(m.inMouseReleased))
	r.Register("INPUT.MOUSEWHEELMOVE", "input", runtime.AdaptLegacy(m.inMouseWheelMove))
	r.Register("INPUT.MOUSEDELTAX", "input", runtime.AdaptLegacy(m.inMouseDeltaX))
	r.Register("INPUT.MOUSEDELTAY", "input", runtime.AdaptLegacy(m.inMouseDeltaY))
	r.Register("INPUT.MOUSEDELTA", "input", runtime.AdaptLegacy(m.inputMouseDelta))
	r.Register("INPUT.SETMOUSEPOS", "input", runtime.AdaptLegacy(m.inSetMousePos))
	r.Register("INPUT.CHARPRESSED", "input", runtime.AdaptLegacy(m.inCharPressed))
	r.Register("INPUT.ISGAMEPADAVAILABLE", "input", runtime.AdaptLegacy(m.inIsGamepadAvailable))
	r.Register("INPUT.GETGAMEPADAXISVALUE", "input", runtime.AdaptLegacy(m.inGetGamepadAxisValue))

	// Gestures (gesture_cgo.go)
	r.Register("GESTURE.ENABLE", "input", runtime.AdaptLegacy(m.gestureEnable))
	r.Register("GESTURE.ISDETECTED", "input", runtime.AdaptLegacy(m.gestureIsDetected))
	r.Register("GESTURE.GETDETECTED", "input", runtime.AdaptLegacy(m.gestureGetDetected))
	r.Register("GESTURE.GETHOLDDURATION", "input", runtime.AdaptLegacy(m.gestureGetHoldDuration))
	r.Register("GESTURE.GETDRAGVECTORX", "input", runtime.AdaptLegacy(m.gestureGetDragVectorX))
	r.Register("GESTURE.GETDRAGVECTORY", "input", runtime.AdaptLegacy(m.gestureGetDragVectorY))
	r.Register("GESTURE.GETDRAGANGLE", "input", runtime.AdaptLegacy(m.gestureGetDragAngle))
	r.Register("GESTURE.GETPINCHVECTORX", "input", runtime.AdaptLegacy(m.gestureGetPinchVectorX))
	r.Register("GESTURE.GETPINCHVECTORY", "input", runtime.AdaptLegacy(m.gestureGetPinchVectorY))
	r.Register("GESTURE.GETPINCHANGLE", "input", runtime.AdaptLegacy(m.gestureGetPinchAngle))

	// Cursor (cursor_cgo.go)
	r.Register("INPUT.LOCKMOUSE", "input", runtime.AdaptLegacy(m.inputLockMouse))
	r.Register("CURSOR.SHOW", "input", runtime.AdaptLegacy(m.cursorShow))
	r.Register("CURSOR.HIDE", "input", runtime.AdaptLegacy(m.cursorHide))
	r.Register("CURSOR.ISHIDDEN", "input", runtime.AdaptLegacy(m.cursorIsHidden))
	r.Register("CURSOR.ISONSCREEN", "input", runtime.AdaptLegacy(m.cursorIsOnScreen))
	r.Register("CURSOR.ENABLE", "input", runtime.AdaptLegacy(m.cursorEnable))
	r.Register("CURSOR.DISABLE", "input", runtime.AdaptLegacy(m.cursorDisable))
	r.Register("CURSOR.ISENABLED", "input", runtime.AdaptLegacy(m.cursorIsEnabled))
	r.Register("CURSOR.SET", "input", runtime.AdaptLegacy(m.cursorSet))

	// Actions (action_builtins.go)
	r.Register("ACTION.DOWN", "input", runtime.AdaptLegacy(m.inActionDown))
	r.Register("ACTION.PRESSED", "input", runtime.AdaptLegacy(m.inActionPressed))
	r.Register("ACTION.RELEASED", "input", runtime.AdaptLegacy(m.inActionReleased))
	r.Register("ACTION.VALUE", "input", runtime.AdaptLegacy(m.inActionAxis))
	r.Register("ACTION.MAPKEY", "input", runtime.AdaptLegacy(m.inMapKey))
	r.Register("ACTION.MAPMOUSE", "input", runtime.AdaptLegacy(m.inMapMouse))
	r.Register("ACTION.MAPJOY", "input", runtime.AdaptLegacy(m.inMapJoy))
	r.Register("ACTION.MAPAXIS", "input", runtime.AdaptLegacy(m.inMapGamepadAxis))
	r.Register("ACTION.RESET", "input", runtime.AdaptLegacy(m.inActionReset))

	// Blitz compatibility (blitz_mousekeys_cgo.go, blitz_aliases_cgo.go, extra_cgo.go)
	r.Register("MouseDown", "input", runtime.AdaptLegacy(m.inMouseDown))
	r.Register("MouseHit", "input", runtime.AdaptLegacy(m.inMouseHit))
	r.Register("KeyDown", "input", runtime.AdaptLegacy(m.inKeyDown))
	r.Register("KeyHit", "input", runtime.AdaptLegacy(m.inKeyHit))
	r.Register("GetJoy", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("GETJOY", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("JoyDown", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("JoyHit", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("JoyX", "input", runtime.AdaptLegacy(m.inJoyX))
	r.Register("JoyY", "input", runtime.AdaptLegacy(m.inJoyY))
	r.Register("JoyZ", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("JoyU", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("JoyV", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("JoyPitch", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("JoyYaw", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("JoyRoll", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("JoyHat", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("JoyXDir", "input", runtime.AdaptLegacy(m.inJoyX))
	r.Register("JoyYDir", "input", runtime.AdaptLegacy(m.inJoyY))

	// Additional Blitz/Legacy aliases (blitz_aliases_cgo.go)
	r.Register("INPUT.KEYHIT", "input", runtime.AdaptLegacy(m.inKeyHit))
	r.Register("INPUT.MOUSEXSPEED", "input", runtime.AdaptLegacy(m.inMouseXSpeed))
	r.Register("INPUT.MOUSEYSPEED", "input", runtime.AdaptLegacy(m.inMouseYSpeed))
	r.Register("INPUT.JOYX", "input", runtime.AdaptLegacy(m.inJoyX))
	r.Register("INPUT.JOYY", "input", runtime.AdaptLegacy(m.inJoyY))
	r.Register("INPUT.JOYBUTTON", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("INPUT.JOYDOWN", "input", runtime.AdaptLegacy(m.inJoyButton))

	r.Register("MOUSEDX", "input", runtime.AdaptLegacy(m.inMouseXSpeed))
	r.Register("INPUT.MOUSEDX", "input", runtime.AdaptLegacy(m.inMouseXSpeed))
	r.Register("MOUSEDY", "input", runtime.AdaptLegacy(m.inMouseYSpeed))
	r.Register("INPUT.MOUSEDY", "input", runtime.AdaptLegacy(m.inMouseYSpeed))
	r.Register("MOUSEWHEEL", "input", runtime.AdaptLegacy(m.inMouseWheel))
	r.Register("INPUT.MOUSEWHEEL", "input", runtime.AdaptLegacy(m.inMouseWheel))
	r.Register("MouseWheel", "input", runtime.AdaptLegacy(m.inMouseWheel))
	r.Register("MOUSEX", "input", runtime.AdaptLegacy(m.mouseXGlobal)) // Linked to facade
	r.Register("MOUSEY", "input", runtime.AdaptLegacy(m.mouseYGlobal)) // Linked to facade
	r.Register("MOUSEZ", "input", runtime.AdaptLegacy(m.inMouseWheel))
	r.Register("KEYHIT", "input", runtime.AdaptLegacy(m.inKeyHit))
	r.Register("KEYDOWN", "input", runtime.AdaptLegacy(m.inKeyDown))
	r.Register("KeyDown", "input", runtime.AdaptLegacy(m.inKeyDown)) // Overlaps with blitz
	r.Register("KEYUP", "input", runtime.AdaptLegacy(m.inKeyReleased))
	r.Register("AXIS", "input", runtime.AdaptLegacy(m.inAxis))

	r.Register("Key", "input", runtime.AdaptLegacy(m.inKeyHit))

	// blitz_mousekeys_cgo.go
	r.Register("FlushMouse", "input", runtime.AdaptLegacy(m.inFlushMouse))
	r.Register("WaitMouse", "input", runtime.AdaptLegacy(m.inWaitMouse))
	r.Register("MoveMouse", "input", runtime.AdaptLegacy(m.inMoveMouse))
	r.Register("HidePointer", "input", runtime.AdaptLegacy(m.inHidePointer))
	r.Register("ShowPointer", "input", runtime.AdaptLegacy(m.inShowPointer))
	r.Register("GetKey", "input", runtime.AdaptLegacy(m.inGetKey))
	r.Register("GETKEY", "input", runtime.AdaptLegacy(m.inGetKey))
	r.Register("WaitKey", "input", runtime.AdaptLegacy(m.inWaitKey))
	r.Register("FlushKeys", "input", runtime.AdaptLegacy(m.inFlushKeys))

	// Advanced & Touch (extra_cgo.go)
	r.Register("INPUT.MOUSEX", "input", runtime.AdaptLegacy(m.inMouseX))
	r.Register("INPUT.MOUSEY", "input", runtime.AdaptLegacy(m.inMouseY))
	r.Register("INPUT.MOUSEDOWN", "input", runtime.AdaptLegacy(m.inMouseDown))
	r.Register("INPUT.MOUSEHIT", "input", runtime.AdaptLegacy(m.inMouseHit))
	r.Register("INPUT.SETMOUSESCALE", "input", runtime.AdaptLegacy(m.inSetMouseScale))
	r.Register("INPUT.SETMOUSEOFFSET", "input", runtime.AdaptLegacy(m.inSetMouseOffset))
	r.Register("INPUT.GETMOUSEWORLDPOS", "input", runtime.AdaptLegacy(m.inGetMouseWorldPos))
	r.Register("INPUT.TOUCHCOUNT", "input", runtime.AdaptLegacy(m.inTouchCount))
	r.Register("INPUT.TOUCHX", "input", runtime.AdaptLegacy(m.inTouchX))
	r.Register("INPUT.TOUCHY", "input", runtime.AdaptLegacy(m.inTouchY))
	r.Register("INPUT.TOUCHPRESSED", "input", runtime.AdaptLegacy(m.inTouchPressed))
	r.Register("INPUT.GETTOUCHPOINTID", "input", runtime.AdaptLegacy(m.inGetTouchPointID))
	r.Register("INPUT.GAMEPADBUTTONCOUNT", "input", runtime.AdaptLegacy(m.inGamepadButtonCount))
	r.Register("INPUT.GAMEPADAXISCOUNT", "input", runtime.AdaptLegacy(m.inGamepadAxisCount))
	r.Register("INPUT.SETGAMEPADMAPPINGS", "input", runtime.AdaptLegacy(m.inSetGamepadMappings))

	// Action Mapping (action_builtins.go)
	r.Register("INPUT.MAPKEY", "input", runtime.AdaptLegacy(m.inMapKey))
	r.Register("INPUT.MAPGAMEPADBUTTON", "input", runtime.AdaptLegacy(m.inMapGamepadButton))
	r.Register("INPUT.MAPGAMEPADAXIS", "input", runtime.AdaptLegacy(m.inMapGamepadAxis))
	r.Register("INPUT.ACTIONPRESSED", "input", runtime.AdaptLegacy(m.inActionPressed))
	r.Register("INPUT.ACTIONDOWN", "input", runtime.AdaptLegacy(m.inActionDown))
	r.Register("INPUT.ACTIONRELEASED", "input", runtime.AdaptLegacy(m.inActionReleased))
	r.Register("INPUT.ACTIONAXIS", "input", runtime.AdaptLegacy(m.inActionAxis))
	r.Register("INPUT.SAVEMAPPINGS", "input", runtime.AdaptLegacy(m.inSaveMappings))
	r.Register("INPUT.LOADMAPPINGS", "input", runtime.AdaptLegacy(m.inLoadMappings))

	// GAME.* aliases for manifest compatibility
	r.Register("GAME.KEYDOWN", "input", runtime.AdaptLegacy(m.inKeyDown))
	r.Register("GAME.KEYPRESSED", "input", runtime.AdaptLegacy(m.inKeyPressed))
	r.Register("GAME.KEYRELEASED", "input", runtime.AdaptLegacy(m.inKeyReleased))
	r.Register("GAME.KEYHIT", "input", runtime.AdaptLegacy(m.inKeyHit))
	r.Register("GAME.KEYCHAR", "input", runtime.AdaptLegacy(m.inCharPressed))
	r.Register("GAME.MOUSEX", "input", runtime.AdaptLegacy(m.mouseXGlobal))
	r.Register("GAME.MOUSEY", "input", runtime.AdaptLegacy(m.mouseYGlobal))
	r.Register("GAME.MOUSEXSPEED", "input", runtime.AdaptLegacy(m.inMouseXSpeed))
	r.Register("GAME.MOUSEYSPEED", "input", runtime.AdaptLegacy(m.inMouseYSpeed))
	r.Register("GAME.MDX", "input", runtime.AdaptLegacy(m.inMouseDeltaX))
	r.Register("GAME.MDY", "input", runtime.AdaptLegacy(m.inMouseDeltaY))
	r.Register("GAME.MLEFT", "input", runtime.AdaptLegacy(m.inMouseDown))
	r.Register("GAME.MRIGHT", "input", runtime.AdaptLegacy(m.inMouseDown))
	r.Register("GAME.MMIDDLE", "input", runtime.AdaptLegacy(m.inMouseDown))
	r.Register("GAME.MWHEEL", "input", runtime.AdaptLegacy(m.mouseWheel))
	r.Register("GAME.JOYX", "input", runtime.AdaptLegacy(m.inJoyX))
	r.Register("GAME.JOYY", "input", runtime.AdaptLegacy(m.inJoyY))
	r.Register("GAME.JOYBUTTON", "input", runtime.AdaptLegacy(m.inJoyButton))
	r.Register("GAME.ANYKEY", "input", runtime.AdaptLegacy(m.inAnyKey))
	r.Register("GAME.MX", "input", runtime.AdaptLegacy(m.mouseXGlobal))
	r.Register("GAME.MY", "input", runtime.AdaptLegacy(m.mouseYGlobal))
	r.Register("GAME.MLEFTPRESSED", "input", runtime.AdaptLegacy(m.inMousePressed))
	r.Register("GAME.MRIGHTPRESSED", "input", runtime.AdaptLegacy(m.inMousePressed))
}
