//go:build !cgo && !windows

package mbparticles

import (
	"fmt"

	"moonbasic/runtime"
	"moonbasic/vm/value"
)

const hint = "PARTICLE natives require CGO: set CGO_ENABLED=1 and install a C compiler, then rebuild"

var stubNames = []string{
	"PARTICLE.MAKE", "PARTICLE.FREE", "PARTICLE.SETTEXTURE", "PARTICLE.SETEMITRATE", "PARTICLE.SETRATE",
	"PARTICLE.SETLIFETIME", "PARTICLE.SETVELOCITY", "PARTICLE.SETDIRECTION", "PARTICLE.SETSPREAD", "PARTICLE.SETSPEED",
	"PARTICLE.SETSTARTSIZE", "PARTICLE.SETENDSIZE",
	"PARTICLE.SETCOLOR", "PARTICLE.SETSTARTCOLOR", "PARTICLE.SETCOLOREND", "PARTICLE.SETENDCOLOR",
	"PARTICLE.SETSIZE", "PARTICLE.SETGRAVITY", "PARTICLE.SETPOS", "PARTICLE.SETBURST", "PARTICLE.SETBILLBOARD",
	"PARTICLE.PLAY", "PARTICLE.STOP", "PARTICLE.UPDATE", "PARTICLE.DRAW", "PARTICLE.ISALIVE", "PARTICLE.COUNT",
	"PARTICLE3D.MAKE", "PARTICLE3D.FREE", "PARTICLE3D.SETTEXTURE", "PARTICLE3D.SETEMITRATE", "PARTICLE3D.SETRATE",
	"PARTICLE3D.SETLIFETIME", "PARTICLE3D.SETVELOCITY", "PARTICLE3D.SETDIRECTION", "PARTICLE3D.SETSPREAD", "PARTICLE3D.SETSPEED",
	"PARTICLE3D.SETSTARTSIZE", "PARTICLE3D.SETENDSIZE",
	"PARTICLE3D.SETCOLOR", "PARTICLE3D.SETSTARTCOLOR", "PARTICLE3D.SETCOLOREND", "PARTICLE3D.SETENDCOLOR",
	"PARTICLE3D.SETSIZE", "PARTICLE3D.SETGRAVITY", "PARTICLE3D.SETPOS", "PARTICLE3D.SETBURST", "PARTICLE3D.SETBILLBOARD",
	"PARTICLE3D.PLAY", "PARTICLE3D.STOP", "PARTICLE3D.UPDATE", "PARTICLE3D.DRAW", "PARTICLE3D.ISALIVE", "PARTICLE3D.COUNT",
}

// Register implements runtime.Module.
func (m *Module) Register(reg runtime.Registrar) {
	for _, name := range stubNames {
		n := name
		reg.Register(n, "particle", func(rt *runtime.Runtime, args ...value.Value) (value.Value, error) {
			_ = rt
			return value.Nil, fmt.Errorf("%s: %s", n, hint)
		})
	}
}

// Shutdown implements runtime.Module.
func (m *Module) Shutdown() {}
