//go:build !cgo

package mbmodel3d

import (
	"fmt"

	"moonbasic/runtime"
	"moonbasic/vm/value"
)

const hint = "MESH/MATERIAL/MODEL/SHADER natives require CGO: set CGO_ENABLED=1 and install a C compiler, then rebuild"

var stubNames = []string{
	"MESH.MAKEPOLY", "MESH.MAKEPLANE", "MESH.MAKECUBE", "MESH.MAKESPHERE", "MESH.MAKECYLINDER",
	"MESH.MAKECONE", "MESH.MAKETORUS", "MESH.MAKEKNOT", "MESH.MAKEHEIGHTMAP", "MESH.MAKECUBICMAP",
	"MESH.CUBE", "MESH.SPHERE", "MESH.PLANE",
	"MESH.UPLOAD", "MESH.DRAW", "MESH.DRAWROTATED", "MESH.UPDATEVERTEX",
	"MESH.GETBBOXMINX", "MESH.GETBBOXMINY", "MESH.GETBBOXMINZ", "MESH.GETBBOXMAXX", "MESH.GETBBOXMAXY", "MESH.GETBBOXMAXZ",
	"MESH.GENTANGENTS", "MESH.FREE",
	"MATERIAL.MAKEDEFAULT", "MATERIAL.FREE", "MATERIAL.SETSHADER", "MATERIAL.SETTEXTURE", "MATERIAL.SETCOLOR", "MATERIAL.SETFLOAT",
	"SHADER.LOAD",
	"MODEL.LOAD", "MODEL.FREE", "MODEL.GETMATERIALCOUNT",
	"MODEL.SETMATERIAL", "MODEL.SETMATERIALTEXTURE", "MODEL.SETMATERIALSHADER", "MODEL.SETMODELMESHMATERIAL",
	"MODEL.SETTEXTURESTAGE", "MODEL.SETSTAGEBLEND", "MODEL.SETSTAGESCROLL", "MODEL.SETSTAGESCALE", "MODEL.SETSTAGEROTATE",
	"MODEL.SCROLLTEXTURE", "MODEL.SCALETEXTURE", "MODEL.ROTATETEXTURE",
	"MODEL.SETALPHA", "MODEL.SETWIREFRAME", "MODEL.SETCULL", "MODEL.SETLIGHTING", "MODEL.SETFOG",
	"MODEL.SETBLEND", "MODEL.SETDEPTH", "MODEL.SETDIFFUSE", "MODEL.SETSPECULAR", "MODEL.SETSPECULARPOW",
	"MODEL.SETEMISSIVE", "MODEL.SETAMBIENTCOLOR",
	"MODEL.CLONE", "MODEL.INSTANCE", "MODEL.ATTACHTO", "MODEL.DETACH", "MODEL.EXISTS",
	"MODEL.SETGPUSKINNING",
}

// Register implements runtime.Module.
func (m *Module) Register(reg runtime.Registrar) {
	for _, name := range stubNames {
		n := name
		reg.Register(n, "model3d", func(rt *runtime.Runtime, args ...value.Value) (value.Value, error) {
			_ = rt
			return value.Nil, fmt.Errorf("%s: %s", n, hint)
		})
	}
}

// Shutdown implements runtime.Module.
func (m *Module) Shutdown() {}
