"""Regenerate MASTER_AUDIT*.txt: manifest vs Register, duplicate Register counts."""
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REG_PAT = re.compile(r'Register\(\s*"([^"]+)"')


def register_key_lines() -> list[str]:
    keys: list[str] = []
    for p in (ROOT / "runtime").rglob("*.go"):
        if p.name.endswith("_test.go"):
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        for m in REG_PAT.finditer(text):
            keys.append(m.group(1))
    return keys


def main() -> None:
    keys = register_key_lines()
    uniq = sorted(set(keys))
    (ROOT / "MASTER_AUDIT_REGISTERED.txt").write_text(
        "\n".join(uniq) + "\n", encoding="utf-8"
    )

    data = json.loads(
        (ROOT / "compiler" / "builtinmanifest" / "commands.json").read_text(
            encoding="utf-8"
        )
    )
    man = {c["key"] for c in data["commands"]}
    mkeys = sorted(man)
    (ROOT / "MASTER_AUDIT_MANIFEST.txt").write_text(
        "\n".join(mkeys) + "\n", encoding="utf-8"
    )

    ctr = Counter(keys)
    dup_lines = [
        "# Keys that appear more than once in Register(\"...\") under runtime/**/*.go (excludes *_test.go).",
        "# Count 2 is normal when the same key is registered in stub + cgo implementations.",
        "",
    ]
    for k, n in sorted(ctr.items()):
        if n > 1:
            dup_lines.append(f"{k} {n}")
    (ROOT / "MASTER_AUDIT_DUPLICATES.txt").write_text(
        "\n".join(dup_lines) + "\n", encoding="utf-8"
    )

    reg = set(keys)
    both = sorted(man & reg)
    miss = sorted(man - reg)
    doconly = sorted(reg - man)
    lines = [
        "# MASTER_AUDIT.txt — manifest key vs runtime Register(\"KEY\")",
        "# Generated by tools/gen_master_audit.py",
        "# DONE=in both; MISSING=in manifest only; DOCONLY=registered but not in manifest.",
        "# PARTIAL reserved for manual follow-up during Groups 1–11.",
        "",
    ]
    for k in both:
        lines.append(f"{k}\tDONE")
    for k in miss:
        lines.append(f"{k}\tMISSING")
    for k in doconly:
        lines.append(f"{k}\tDOCONLY")
    (ROOT / "MASTER_AUDIT.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print("registered unique", len(uniq), "Register lines", len(keys))
    print("manifest unique", len(mkeys))
    print("DONE", len(both), "MISSING", len(miss), "DOCONLY", len(doconly))


if __name__ == "__main__":
    main()
