"""Regenerate MASTER_AUDIT*.txt: manifest vs Register, duplicate Register counts."""
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUDIT_DIR = ROOT / "docs" / "audit"
# Enhanced regex to find strings inside Register / reg / regFlat or similar calls.
REG_PAT = re.compile(r'(?:Register|reg|regFlat|reg_alias|RegisterModule)\((.*)\)')
STR_PAT = re.compile(r'"([^"]+)"')

def register_key_lines() -> list[str]:
    """Scan Go source files for registration calls."""
    keys: list[str] = []
    # Scan main runtime and sub-modules
    for p in (ROOT / "runtime").rglob("*.go"):
        if p.name.endswith("_test.go"):
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
            for line in text.splitlines():
                if "Register" in line or 'reg("' in line or 'regFlat("' in line:
                    # Find all strings in this registration-looking line.
                    for m in STR_PAT.finditer(line):
                        s = m.group(1)
                        # Filter out things that are clearly not command keys (namespaces/package names).
                        if s in ("bitwise", "physics2d", "game", "table", "util", "time", "weather", "sky", "water", "draw", "draw3d", "audio", "mblight2d", "mbscene"):
                            continue
                        keys.append(s)
        except Exception:
            continue
    return keys


def main() -> None:
    keys = register_key_lines()
    uniq = sorted(set(keys))
    AUDIT_DIR.mkdir(parents=True, exist_ok=True)
    (AUDIT_DIR / "MASTER_AUDIT_REGISTERED.txt").write_text(
        "\n".join(uniq) + "\n", encoding="utf-8"
    )

    data = json.loads(
        (ROOT / "compiler" / "builtinmanifest" / "commands.json").read_text(
            encoding="utf-8"
        )
    )
    man = {c["key"] for c in data["commands"]}
    mkeys = sorted(man)
    (AUDIT_DIR / "MASTER_AUDIT_MANIFEST.txt").write_text(
        "\n".join(mkeys) + "\n", encoding="utf-8"
    )

    ctr = Counter(keys)
    dup_lines = [
        "# Keys that appear more than once in Register(\"...\") under runtime/**/*.go (excludes *_test.go).",
        "# Count 2 is normal when the same key is registered in stub + cgo implementations.",
        "",
    ]
    for k, n in sorted(ctr.items()):
        if n > 1:
            dup_lines.append(f"{k} {n}")
    (AUDIT_DIR / "MASTER_AUDIT_DUPLICATES.txt").write_text(
        "\n".join(dup_lines) + "\n", encoding="utf-8"
    )

    reg = set(keys)
    both = sorted(man & reg)
    miss = sorted(man - reg)
    doconly = sorted(reg - man)
    lines = [
        "# MASTER_AUDIT.txt — manifest key vs runtime Register(\"KEY\")",
        "# Generated by tools/gen_master_audit.py",
        "# DONE=in both; MISSING=in manifest only; DOCONLY=registered but not in manifest.",
        "# PARTIAL reserved for manual follow-up during Groups 1–11.",
        "",
    ]
    for k in both:
        lines.append(f"{k}\tDONE")
    for k in miss:
        lines.append(f"{k}\tMISSING")
    for k in doconly:
        lines.append(f"{k}\tDOCONLY")
    (AUDIT_DIR / "MASTER_AUDIT.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    write_reference_key_coverage(man)

    print("registered unique", len(uniq), "Register lines", len(keys))
    print("manifest unique", len(mkeys))
    print("DONE", len(both), "MISSING", len(miss), "DOCONLY", len(doconly))


def write_reference_key_coverage(man: set[str]) -> None:
    """Map manifest keys to docs/reference/*.md + language spec (verbatim substring hits)."""
    out_dir = AUDIT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    ref_dir = ROOT / "docs" / "reference"
    spec = ROOT / "compiler" / "errors" / "MoonBasic.md"
    sources: list[tuple[str, Path]] = []
    if ref_dir.is_dir():
        for p in sorted(ref_dir.glob("*.md")):
            sources.append((f"docs/reference/{p.name}", p))
    if spec.is_file():
        sources.append(("compiler/errors/MoonBasic.md", spec))

    per_file: list[tuple[str, int]] = []
    never: set[str] = set(man)
    for label, path in sources:
        text = path.read_text(encoding="utf-8", errors="replace")
        n = 0
        for k in man:
            if k in text:
                n += 1
                never.discard(k)
        per_file.append((label, n))

    lines = [
        "# REFERENCE_KEY_COVERAGE.txt — manifest keys vs prose docs (verbatim substring)",
        "# Generated by tools/gen_master_audit.py",
        "# A key counts as \"covered\" if it appears verbatim in the markdown source.",
        "# False negatives: aliases, tables split across lines, or KEY$ variants spelled differently.",
        "",
        "# Per-file hit counts (same key may appear in multiple files)",
        f"# {'path':<48} hits",
    ]
    for label, n in sorted(per_file):
        lines.append(f"{label:<50}{n}")
    lines.extend(
        [
            "",
            f"# Manifest keys with no hit in any scanned doc ({len(never)} total)",
            "",
        ]
    )
    lines.extend(sorted(never))
    lines.append("")
    (out_dir / "REFERENCE_KEY_COVERAGE.txt").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )
    print("reference coverage: manifest keys never in reference/spec:", len(never))


if __name__ == "__main__":
    main()
